CREATE TYPE "ContentScheduleStatus" AS ENUM ('DRAFT','READY','QUEUED','PROCESSING','COMPLETED','PARTIALLY_COMPLETED','FAILED','CANCELLED');
CREATE TABLE "ContentSchedule" ("id" TEXT PRIMARY KEY,"organisationId" TEXT NOT NULL,"projectId" TEXT NOT NULL,"brandId" TEXT NOT NULL,"contentItemId" TEXT NOT NULL,"contentVariantId" TEXT NOT NULL,"socialAccountId" TEXT NOT NULL,"scheduledFor" TIMESTAMP(3) NOT NULL,"timezone" TEXT NOT NULL,"status" "ContentScheduleStatus" NOT NULL DEFAULT 'DRAFT',"recurrence" JSONB,"occurrenceIndex" INTEGER NOT NULL DEFAULT 1,"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"cancelledAt" TIMESTAMP(3));
CREATE TABLE "PublishingWindow" ("id" TEXT PRIMARY KEY,"organisationId" TEXT NOT NULL,"brandId" TEXT NOT NULL,"provider" "SocialProvider" NOT NULL,"timezone" TEXT NOT NULL,"weekdays" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],"startMinute" INTEGER NOT NULL,"endMinute" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "PublishingJob" ("id" TEXT PRIMARY KEY,"organisationId" TEXT NOT NULL,"projectId" TEXT NOT NULL,"brandId" TEXT NOT NULL,"contentScheduleId" TEXT NOT NULL,"idempotencyKey" TEXT NOT NULL,"status" "ContentScheduleStatus" NOT NULL DEFAULT 'QUEUED',"attemptCount" INTEGER NOT NULL DEFAULT 0,"maxAttempts" INTEGER NOT NULL DEFAULT 3,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PublishingAttempt" ("id" TEXT PRIMARY KEY,"publishingJobId" TEXT NOT NULL,"attemptNumber" INTEGER NOT NULL,"status" TEXT NOT NULL,"providerResponse" JSONB,"errorMessage" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "SchedulingConflict" ("id" TEXT PRIMARY KEY,"contentScheduleId" TEXT NOT NULL,"conflictType" TEXT NOT NULL,"message" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "CalendarNote" ("id" TEXT PRIMARY KEY,"organisationId" TEXT NOT NULL,"projectId" TEXT,"brandId" TEXT,"noteDate" TIMESTAMP(3) NOT NULL,"timezone" TEXT NOT NULL,"body" TEXT NOT NULL,"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "ContentSchedule_contentVariantId_scheduledFor_key" ON "ContentSchedule"("contentVariantId","scheduledFor"); CREATE UNIQUE INDEX "PublishingJob_contentScheduleId_idempotencyKey_key" ON "PublishingJob"("contentScheduleId","idempotencyKey"); CREATE UNIQUE INDEX "PublishingAttempt_publishingJobId_attemptNumber_key" ON "PublishingAttempt"("publishingJobId","attemptNumber");
ALTER TABLE "ContentSchedule" ADD FOREIGN KEY ("contentItemId") REFERENCES "ContentItem"("id") ON DELETE CASCADE; ALTER TABLE "ContentSchedule" ADD FOREIGN KEY ("contentVariantId") REFERENCES "ContentVariant"("id") ON DELETE CASCADE; ALTER TABLE "ContentSchedule" ADD FOREIGN KEY ("socialAccountId") REFERENCES "SocialAccount"("id") ON DELETE RESTRICT; ALTER TABLE "PublishingJob" ADD FOREIGN KEY ("contentScheduleId") REFERENCES "ContentSchedule"("id") ON DELETE CASCADE; ALTER TABLE "PublishingAttempt" ADD FOREIGN KEY ("publishingJobId") REFERENCES "PublishingJob"("id") ON DELETE CASCADE; ALTER TABLE "SchedulingConflict" ADD FOREIGN KEY ("contentScheduleId") REFERENCES "ContentSchedule"("id") ON DELETE CASCADE;
