/**
 * Development-only fixture for Unified Analytics visual QA.
 * Never imported by production API routes or services.
 */
import type { UnifiedAnalyticsWorkspaceData } from "@/lib/unified-analytics/types";

const baseDateRange = {
  label: "Last 30 days",
  comparisonLabel: "vs previous 30 days",
  from: "2026-07-25T00:00:00.000Z",
  to: "2026-08-24T00:00:00.000Z",
};

const modelOptions = [
  {
    type: "LAST_TOUCH" as const,
    label: "Last Touch",
    description: "Assigns full conversion credit to the final eligible marketing interaction before conversion.",
    maturity: "launch" as const,
  },
  {
    type: "FIRST_TOUCH" as const,
    label: "First Touch",
    description: "Assigns full conversion credit to the first eligible marketing interaction.",
    maturity: "launch" as const,
  },
  {
    type: "LINEAR" as const,
    label: "Linear",
    description: "Distributes credit equally across all eligible touchpoints.",
    maturity: "launch" as const,
  },
];

export const ANALYTICS_VISUAL_PREVIEW_FIXTURE: UnifiedAnalyticsWorkspaceData = {
  hasBrandContext: true,
  dateRange: baseDateRange,
  attributionModel: "LAST_TOUCH",
  attributionModelLabel: "Last Touch",
  lookbackWindowDays: 30,
  freshness: { label: "Updated 12 min ago", state: "fresh" },
  coverage: [
    {
      dimension: "Paid Spend Coverage",
      state: "Strong",
      label: "Paid spend data available for selected period",
      coveragePercent: 100,
    },
    {
      dimension: "Organic Analytics Coverage",
      state: "Partial",
      label: "Organic analytics incomplete",
      coveragePercent: 60,
    },
    {
      dimension: "Web Analytics Coverage",
      state: "Strong",
      label: "GA4 sessions and conversion data available",
      coveragePercent: 100,
    },
    {
      dimension: "Conversion Tracking Coverage",
      state: "Partial",
      label: "Attribution based on 72% of tracked conversions",
      coveragePercent: 72,
    },
    {
      dimension: "Revenue Coverage",
      state: "Partial",
      label: "61% of observed revenue attributed",
      coveragePercent: 61,
    },
    {
      dimension: "Attribution Coverage",
      state: "Partial",
      label: "74% of journeys have eligible touchpoints",
      coveragePercent: 74,
    },
  ],
  coverageWarnings: [
    "Organic analytics missing for one or more connected channels.",
    "Attribution is based on 74% of tracked conversion journeys.",
  ],
  executiveKpis: [
    {
      label: "Total Marketing Spend",
      value: "£24,800",
      change: 8.2,
      comparisonLabel: "vs previous 30 days",
      metadata: { kind: "Observed", source: ["MarketingCostRecord"] },
      footnote: "Paid spend only",
    },
    {
      label: "Attributed Revenue",
      value: "£68,400",
      change: 14.5,
      comparisonLabel: "vs previous 30 days",
      metadata: { kind: "Attributed", attributionModel: "Last Touch", coverage: 61 },
      footnote: "Coverage: 61%",
    },
    {
      label: "Conversions",
      value: "186",
      change: 6.3,
      comparisonLabel: "vs previous 30 days",
      metadata: { kind: "Observed" },
    },
    {
      label: "Blended ROAS",
      value: "2.76x",
      change: null,
      comparisonLabel: "vs previous 30 days",
      metadata: { kind: "Calculated", coverage: 61 },
    },
    {
      label: "Organic Reach",
      value: "284.2K",
      change: 12.4,
      comparisonLabel: "vs previous 30 days",
      metadata: { kind: "Observed", source: ["Social analytics providers"] },
    },
    {
      label: "Website Sessions",
      value: "18.4K",
      change: 9.1,
      comparisonLabel: "vs previous 30 days",
      metadata: { kind: "Observed", source: ["GA4"] },
    },
  ],
  channels: [
    {
      channel: "Meta Ads",
      sourceType: "paid",
      spend: 12400,
      reach: null,
      impressions: 842000,
      clicks: 18420,
      engagement: null,
      conversions: 94,
      attributedRevenue: 32400,
      roas: 2.61,
      contributionPercent: 47.4,
      assistPercent: null,
      freshness: "fresh",
      providerReportedConversions: 102,
      crescoTrackedConversions: 88,
    },
    {
      channel: "Google Ads",
      sourceType: "paid",
      spend: 8400,
      reach: null,
      impressions: 412000,
      clicks: 9840,
      engagement: null,
      conversions: 52,
      attributedRevenue: 21800,
      roas: 2.6,
      contributionPercent: 31.9,
      assistPercent: null,
      freshness: "fresh",
      providerReportedConversions: 58,
      crescoTrackedConversions: 48,
    },
    {
      channel: "Instagram Organic",
      sourceType: "organic",
      spend: null,
      reach: 184200,
      impressions: 312000,
      clicks: 4200,
      engagement: 8420,
      conversions: null,
      attributedRevenue: 8400,
      roas: null,
      contributionPercent: 12.3,
      assistPercent: null,
      freshness: "fresh",
      providerReportedConversions: null,
      crescoTrackedConversions: 24,
    },
    {
      channel: "LinkedIn Organic",
      sourceType: "organic",
      spend: null,
      reach: 62000,
      impressions: 98000,
      clicks: 1840,
      engagement: 2140,
      conversions: null,
      attributedRevenue: 5800,
      roas: null,
      contributionPercent: 8.5,
      assistPercent: null,
      freshness: "stale",
      providerReportedConversions: null,
      crescoTrackedConversions: 12,
    },
  ],
  content: [
    {
      contentId: "content-reel-q3",
      title: "Q3 product launch reel",
      format: "Reel",
      organicReach: 48200,
      organicEngagement: 2840,
      paidSpend: null,
      paidRoas: null,
      attributedConversions: 18,
      attributedRevenue: 12400,
      assistedConversions: 42,
      assistedRevenue: 28400,
      channels: ["INSTAGRAM"],
    },
    {
      contentId: "content-carousel-roi",
      title: "ROI calculator carousel",
      format: "Carousel",
      organicReach: 22400,
      organicEngagement: 1420,
      paidSpend: null,
      paidRoas: null,
      attributedConversions: 12,
      attributedRevenue: 8400,
      assistedConversions: 28,
      assistedRevenue: 18200,
      channels: ["LINKEDIN", "INSTAGRAM"],
    },
  ],
  funnel: [
    { stage: "Impressions / Reach", count: 1254000, conversionRate: null, dropOffPercent: null },
    { stage: "Engagement", count: 28420, conversionRate: null, dropOffPercent: null },
    { stage: "Clicks", count: 38420, conversionRate: 3.1, dropOffPercent: null },
    { stage: "Sessions", count: 18420, conversionRate: 47.9, dropOffPercent: 52.1 },
    { stage: "Conversions", count: 186, conversionRate: 1.0, dropOffPercent: null },
    { stage: "Revenue", count: 68400, conversionRate: null, dropOffPercent: null },
  ],
  conversions: [
    {
      id: "conv-meta",
      conversionType: "Attributed",
      count: 88,
      attributedChannel: "Meta Ads",
      attributedCampaign: null,
      attributedContent: null,
      revenue: 32400,
      model: "Last Touch",
      coverage: 61,
    },
    {
      id: "conv-google",
      conversionType: "Attributed",
      count: 48,
      attributedChannel: "Google Ads",
      attributedCampaign: null,
      attributedContent: null,
      revenue: 21800,
      model: "Last Touch",
      coverage: 61,
    },
  ],
  revenue: {
    observedRevenue: 112400,
    attributedRevenue: 68400,
    unattributedRevenue: 44000,
    paidAttributedRevenue: 54200,
    organicAssistedRevenue: 41200,
    attributionCoverage: 61,
  },
  modelComparison: [
    {
      modelType: "LAST_TOUCH",
      modelLabel: "Last Touch",
      channel: "Meta Ads",
      contributionPercent: 47,
      attributedRevenue: 32400,
    },
    {
      modelType: "FIRST_TOUCH",
      modelLabel: "First Touch",
      channel: "Instagram Organic",
      contributionPercent: 38,
      attributedRevenue: 26200,
    },
    {
      modelType: "LINEAR",
      modelLabel: "Linear",
      channel: "Meta Ads",
      contributionPercent: 32,
      attributedRevenue: 21880,
    },
  ],
  journeyFlows: [
    { path: ["Instagram Organic", "Meta Ads"], conversions: 42, revenue: 28400 },
    { path: ["LinkedIn Organic", "Google Ads"], conversions: 28, revenue: 18200 },
  ],
  organicAssist: {
    rate: 34,
    paidConversionsWithPriorOrganic: 32,
    totalPaidAttributedConversions: 94,
    topAssistingChannel: "Instagram Organic",
    description:
      "34% of paid-attributed conversions had a prior organic interaction within the lookback window.",
  },
  unattributed: { conversions: 52, revenue: 44000 },
  attributionConfidence: {
    level: "Medium",
    label: "Partial coverage — interpret channel credit with caution.",
    sourceCoveragePercent: 72,
    journeyCoveragePercent: 74,
    limitations: [
      "28% of conversions cannot be attributed with current tracking.",
      "26% of conversion journeys lack eligible marketing touchpoints.",
    ],
  },
  webAnalytics: {
    connected: true,
    sessions: 18420,
    users: 14280,
    pageviews: 42800,
    conversions: 186,
    freshness: "fresh",
    lastSyncedAt: "2026-08-24T16:48:00.000Z",
    source: "GA4",
  },
  insights: [
    {
      id: "attribution-coverage-issue",
      type: "anomaly",
      severity: "medium",
      title: "Attribution coverage below target",
      explanation:
        "72% of conversions have a known marketing source. 28% cannot be attributed with current data.",
      evidence: [{ label: "Source coverage", value: "72%" }],
      action: { label: "Review integrations", href: "/settings/integrations" },
      category: "cross-channel",
      generatedAt: "2026-08-24T16:00:00.000Z",
      confidence: 0.72,
    },
    {
      id: "organic-assist",
      type: "organic",
      severity: "info",
      title: "Organic content assists paid conversions",
      explanation:
        "34% of paid-attributed conversions had a prior organic interaction. This does not imply causation.",
      evidence: [{ label: "Organic assist rate", value: "34%" }],
      category: "organic",
      generatedAt: "2026-08-24T16:00:00.000Z",
      confidence: 0.65,
    },
  ],
  disclaimer:
    "Attribution reflects tracked touchpoints within the lookback window. Unattributed conversions and revenue remain visible.",
  modelOptions,
};

/** Partial-data state fixture for coverage warning screenshots. */
export const ANALYTICS_PARTIAL_DATA_FIXTURE: UnifiedAnalyticsWorkspaceData = {
  ...ANALYTICS_VISUAL_PREVIEW_FIXTURE,
  coverage: [
    {
      dimension: "Paid Spend Coverage",
      state: "Strong",
      label: "Paid spend data available for selected period",
      coveragePercent: 100,
    },
    {
      dimension: "Organic Analytics Coverage",
      state: "Limited",
      label: "Organic analytics incomplete",
      coveragePercent: 40,
    },
    {
      dimension: "Web Analytics Coverage",
      state: "Unavailable",
      label: "No web analytics connected",
      coveragePercent: null,
    },
    {
      dimension: "Conversion Tracking Coverage",
      state: "Limited",
      label: "Attribution based on 42% of tracked conversions",
      coveragePercent: 42,
    },
    {
      dimension: "Revenue Coverage",
      state: "Unavailable",
      label: "Revenue data not connected",
      coveragePercent: null,
    },
    {
      dimension: "Attribution Coverage",
      state: "Limited",
      label: "38% of journeys have eligible touchpoints",
      coveragePercent: 38,
    },
  ],
  coverageWarnings: [
    "Organic analytics missing for one or more connected channels.",
    "Connect GA4 to measure sessions, landing pages and conversion journeys.",
    "Revenue data not connected.",
    "Attribution is based on 38% of tracked conversion journeys.",
  ],
  executiveKpis: [
    {
      label: "Total Marketing Spend",
      value: "£24,800",
      change: 8.2,
      comparisonLabel: "vs previous 30 days",
      metadata: { kind: "Observed" },
    },
    {
      label: "Conversions",
      value: "186",
      change: 6.3,
      comparisonLabel: "vs previous 30 days",
      metadata: { kind: "Observed" },
    },
  ],
  revenue: {
    observedRevenue: null,
    attributedRevenue: 28400,
    unattributedRevenue: null,
    paidAttributedRevenue: 22400,
    organicAssistedRevenue: null,
    attributionCoverage: null,
  },
  attributionConfidence: {
    level: "Low",
    label: "Limited coverage — many conversions lack marketing source linkage.",
    sourceCoveragePercent: 42,
    journeyCoveragePercent: 38,
    limitations: [
      "58% of conversions cannot be attributed with current tracking.",
      "62% of conversion journeys lack eligible marketing touchpoints.",
      "No observed revenue source connected — revenue attribution is conversion-based only.",
      "Revenue coverage unavailable.",
    ],
  },
  webAnalytics: {
    connected: false,
    sessions: null,
    users: null,
    pageviews: null,
    conversions: null,
    freshness: "unavailable",
    lastSyncedAt: null,
    source: null,
  },
};
