import type { AdvertisingCreativeAssetSource } from "@prisma/client";
import { SYNTHETIC_IMAGE_DISCLAIMER } from "@/lib/advertising-creatives/constants";

export type ProvenanceRecord = {
  source: AdvertisingCreativeAssetSource;
  isSynthetic: boolean;
  provenanceLabel: string;
  syntheticDisclaimer?: string;
  marketingAssetId?: string;
  visualProjectId?: string;
};

export function buildProvenance(input: {
  source: AdvertisingCreativeAssetSource;
  isSynthetic?: boolean;
  marketingAssetId?: string;
  visualProjectId?: string;
  explicitSourceLabel?: string;
}): ProvenanceRecord {
  const isSynthetic =
    input.isSynthetic ??
    ["AI_IMAGE_STUDIO", "AI_CAROUSEL_STUDIO", "AI_VIDEO_PIPELINE"].includes(input.source);

  const provenanceLabel =
    input.explicitSourceLabel ??
    ({
      ASSET_LIBRARY: "Approved asset from Asset Library",
      AI_IMAGE_STUDIO: "Generated by AI Image Studio",
      AI_CAROUSEL_STUDIO: "Generated by Carousel Studio",
      AI_VIDEO_PIPELINE: "Generated by AI Video/Reels Pipeline",
      UPLOAD: "User upload",
      EXTERNAL: "External source — verify rights",
    }[input.source] ?? "Unknown source");

  return {
    source: input.source,
    isSynthetic,
    provenanceLabel,
    syntheticDisclaimer: isSynthetic ? SYNTHETIC_IMAGE_DISCLAIMER : undefined,
    marketingAssetId: input.marketingAssetId,
    visualProjectId: input.visualProjectId,
  };
}

export function assertSyntheticLabelling(provenance: ProvenanceRecord): string[] {
  const warnings: string[] = [];
  if (provenance.isSynthetic && !provenance.syntheticDisclaimer) {
    warnings.push("Synthetic media must include a disclaimer label.");
  }
  if (
    provenance.isSynthetic &&
    /\b(real customer|our office|actual result|live event)\b/i.test(provenance.provenanceLabel)
  ) {
    warnings.push("Synthetic media must not be labelled as a real customer, office, result, or event.");
  }
  return warnings;
}
