/**
 * Development-only fixture for Command Centre visual QA.
 * Never imported by production API routes or services.
 */
import { BrandStatus, OrganisationStatus, ProjectStatus } from "@prisma/client";
import type { MarketingCommandCentreData } from "@/server/services/marketing-command-centre-service";
import type { workspaceService } from "@/server/services/workspace-service";

type ResolvedWorkspace = Awaited<ReturnType<typeof workspaceService.getResolvedWorkspace>>;

const previewWorkspace: ResolvedWorkspace = {
  organisations: [
    {
      id: "org-preview",
      name: "Cresco Holdings",
      slug: "cresco-holdings",
      legalName: null,
      website: null,
      logoUrl: null,
      industry: null,
      countryCode: null,
      defaultTimezone: "UTC",
      status: OrganisationStatus.ACTIVE,
      createdByUserId: "user-preview",
      createdAt: new Date("2026-01-01T00:00:00.000Z"),
      updatedAt: new Date("2026-01-01T00:00:00.000Z"),
      archivedAt: null,
    },
  ],
  projects: [
    {
      id: "project-preview",
      organisationId: "org-preview",
      name: "Growth Platform",
      slug: "growth-platform",
      description: null,
      website: null,
      status: ProjectStatus.ACTIVE,
      createdByUserId: "user-preview",
      createdAt: new Date("2026-01-01T00:00:00.000Z"),
      updatedAt: new Date("2026-01-01T00:00:00.000Z"),
      archivedAt: null,
    },
  ],
  brands: [
    {
      id: "brand-preview",
      organisationId: "org-preview",
      projectId: "project-preview",
      name: "Cresco AI",
      slug: "cresco-ai",
      description: null,
      website: null,
      primaryDomain: null,
      logoUrl: null,
      faviconUrl: null,
      primaryColour: null,
      secondaryColour: null,
      accentColour: null,
      analyticsTimezone: null,
      status: BrandStatus.ACTIVE,
      createdByUserId: "user-preview",
      createdAt: new Date("2026-01-01T00:00:00.000Z"),
      updatedAt: new Date("2026-01-01T00:00:00.000Z"),
      archivedAt: null,
      profile: null,
    },
  ],
  preference: {
    currentOrganisationId: "org-preview",
    currentProjectId: "project-preview",
    currentBrandId: "brand-preview",
    onboardingCompletedAt: new Date("2026-01-01T00:00:00.000Z"),
    onboardingStep: null,
  },
};

export const COMMAND_CENTRE_VISUAL_PREVIEW_FIXTURE: MarketingCommandCentreData = {
  workspace: previewWorkspace,
  hasBrandContext: true,
  dateRange: {
    preset: "30d",
    from: new Date("2026-07-24").toISOString(),
    to: new Date("2026-08-23").toISOString(),
    label: "Last 30 days",
    comparisonLabel: "vs previous 30 days",
  },
  executiveKpis: [
    {
      label: "Total Spend",
      value: "£42,180",
      change: 8.4,
      comparisonLabel: "vs previous 30 days",
      sparkline: [3200, 4100, 3900, 4500, 4200, 4800, 5100],
      state: "normal",
    },
    {
      label: "Revenue Influenced",
      value: "£186,420",
      change: 12.1,
      comparisonLabel: "vs previous 30 days",
      sparkline: [12000, 13500, 12800, 15000, 16200, 15800, 17100],
      state: "normal",
    },
    {
      label: "Conversions",
      value: "1,243",
      change: -2.3,
      comparisonLabel: "vs previous 30 days",
      sparkline: [38, 42, 40, 36, 41, 39, 37],
      state: "normal",
    },
    {
      label: "Blended ROAS",
      value: "4.42x",
      change: 5.6,
      comparisonLabel: "vs previous 30 days",
      sparkline: [3.8, 4.1, 4.0, 4.3, 4.2, 4.5, 4.4],
      state: "normal",
    },
    {
      label: "Marketing Health",
      value: "63 / 100",
      change: 12,
      comparisonLabel: "vs previous 30 days",
      state: "normal",
    },
  ],
  paidSummary: {
    spend: "£42,180",
    roas: "4.42x",
    conversions: "1,243",
    cpa: "£33.93",
    activeCampaigns: "8",
  },
  organicSummary: {
    reach: "284K",
    engagement: "18.4K",
    profileVisits: "6.2K",
    shares: "1.1K",
    postsPublished: "14",
  },
  paidChannels: [],
  organicChannels: [],
  organicChannelPerformance: [
    {
      provider: "LINKEDIN",
      channel: "LinkedIn",
      connected: true,
      reach: 98400,
      views: null,
      engagement: 12400,
      engagementRate: 4.7,
      followers: 12400,
      followerGrowth: 820,
      shares: 420,
      saves: null,
      published: 12,
      scheduled: 3,
      dataFreshness: new Date(),
      unavailableMetrics: [],
    },
    {
      provider: "X",
      channel: "X",
      connected: true,
      reach: 41200,
      views: null,
      engagement: 3120,
      engagementRate: 2.1,
      followers: 3200,
      followerGrowth: 120,
      shares: 180,
      saves: null,
      published: 8,
      scheduled: 0,
      dataFreshness: new Date(),
      unavailableMetrics: [],
    },
    {
      provider: "INSTAGRAM",
      channel: "Instagram",
      connected: false,
      reach: null,
      views: null,
      engagement: null,
      engagementRate: null,
      followers: null,
      followerGrowth: null,
      shares: null,
      saves: null,
      published: 0,
      scheduled: 0,
      dataFreshness: null,
      unavailableMetrics: [],
    },
  ],
  previousOrganicChannelPerformance: [
    {
      provider: "LINKEDIN",
      channel: "LinkedIn",
      connected: true,
      reach: 83200,
      views: null,
      engagement: 10200,
      engagementRate: 4.1,
      followers: 11600,
      followerGrowth: 640,
      shares: 360,
      saves: null,
      published: 10,
      scheduled: 2,
      dataFreshness: new Date(),
      unavailableMetrics: [],
    },
    {
      provider: "X",
      channel: "X",
      connected: true,
      reach: 38800,
      views: null,
      engagement: 2800,
      engagementRate: 1.9,
      followers: 3080,
      followerGrowth: 90,
      shares: 150,
      saves: null,
      published: 6,
      scheduled: 0,
      dataFreshness: new Date(),
      unavailableMetrics: [],
    },
    {
      provider: "INSTAGRAM",
      channel: "Instagram",
      connected: false,
      reach: null,
      views: null,
      engagement: null,
      engagementRate: null,
      followers: null,
      followerGrowth: null,
      shares: null,
      saves: null,
      published: 0,
      scheduled: 0,
      dataFreshness: null,
      unavailableMetrics: [],
    },
  ],
  paidChart: { spend: [], revenue: [], conversions: [], roas: [], cpa: [] },
  publishingQueue: [],
  calendarPreview: [],
  insights: [
    {
      id: "insight-1",
      type: "opportunity",
      severity: "high",
      title: "Increase budget for Campaign A",
      explanation: "High-performing creative and audience combination with sustained ROAS above target.",
      evidence: [
        { label: "ROAS", value: "5.8x" },
        { label: "Spend", value: "£8,420" },
      ],
      estimatedImpact: "+£8,400 estimated revenue",
      action: { label: "Review", href: "/advertising" },
      category: "paid",
      generatedAt: new Date().toISOString(),
      confidence: 0.86,
    },
    {
      id: "insight-2",
      type: "creative-fatigue",
      severity: "medium",
      title: "Creative fatigue detected on Meta",
      explanation: "CTR has declined for 14 days while frequency increased.",
      evidence: [{ label: "CTR change", value: "-18%" }],
      estimatedImpact: "Reduce wasted spend",
      action: { label: "Create experiment", href: "/experiments" },
      category: "paid",
      generatedAt: new Date().toISOString(),
      confidence: 0.62,
    },
    {
      id: "insight-organic-1",
      type: "organic",
      severity: "medium",
      title: "LinkedIn is outperforming organic baseline",
      explanation: "LinkedIn delivered 4.7% engagement during last 30 days, above the organic average.",
      evidence: [
        { label: "Channel engagement rate", value: "4.70%" },
        { label: "Organic average", value: "3.20%" },
      ],
      estimatedImpact: "Create more content in this high-performing format",
      action: { label: "View growth", href: "/organic-social/growth" },
      category: "organic",
      generatedAt: new Date().toISOString(),
      confidence: 0.78,
    },
  ],
  health: {
    total: 63,
    components: [
      {
        key: "paid",
        label: "Paid performance",
        score: 18,
        maxScore: 25,
        detail: "Blended ROAS 4.42x across 2 connected paid channel(s).",
        recommendedImprovement: "Review underperforming campaigns and reallocate budget to higher ROAS segments.",
      },
      {
        key: "organic",
        label: "Organic performance",
        score: 14,
        maxScore: 25,
        detail: "Organic activity across 2 connected channel(s).",
      },
      {
        key: "publishing",
        label: "Publishing consistency",
        score: 12,
        maxScore: 20,
        detail: "14 published and 3 scheduled in the selected period.",
      },
      {
        key: "connectivity",
        label: "Channel connectivity",
        score: 7,
        maxScore: 15,
        detail: "2 of 4 paid and 2 of 5 organic channels connected.",
        recommendedImprovement: "Connect 2 paid and 3 organic channel(s) to improve marketing coverage.",
      },
      {
        key: "dataQuality",
        label: "Data quality",
        score: 12,
        maxScore: 15,
        detail: "Paid data is fresh; organic data is delayed.",
      },
    ],
  },
  coverage: {
    paid: "2 of 4 paid channels connected",
    organic: "2 of 5 organic channels connected",
    note: undefined,
  },
  freshness: {
    paid: "Updated 12 minutes ago",
    organic: "Syncing",
    paidState: "fresh",
    organicState: "delayed",
  },
  currency: "GBP",
  hasPaidConnections: true,
  hasOrganicConnections: true,
  priorities: [
    {
      id: "alert-1",
      type: "integration",
      title: "Meta Ads connection needs attention",
      urgency: "critical",
      context: "Data has been stale for 6 hours",
      targetLabel: "META",
      action: { label: "Fix connection", href: "/integrations" },
    },
    {
      id: "pending-approvals",
      type: "approval",
      title: "2 campaigns need approval",
      urgency: "high",
      context: "£7,450 budget",
      action: { label: "Review", href: "/publishing" },
    },
    {
      id: "due-today",
      type: "publication",
      title: "3 content items ready to publish",
      urgency: "high",
      context: "Due today",
      action: { label: "Review queue", href: "/publishing" },
    },
    {
      id: "experiments-ready",
      type: "experiment",
      title: "1 experiment ready for review",
      urgency: "normal",
      context: "Results available for review",
      action: { label: "Review", href: "/experiments" },
    },
  ],
  funnel: [
    { stage: "Impressions", count: 2456789, availability: "available" },
    { stage: "Clicks", count: 45678, rateLabel: "CTR", rateValue: "1.86%", availability: "available" },
    { stage: "Landing page views", count: 12430, rateLabel: "Visit rate", rateValue: "27.21%", availability: "available" },
    { stage: "Conversions", count: 1243, rateLabel: "CVR", rateValue: "10.00%", availability: "available" },
    { stage: "Revenue", count: 186420, rateValue: "£186,420", availability: "available" },
  ],
  recentActivity: [
    {
      id: "activity-1",
      type: "alert",
      description: "Meta sync delayed",
      timestamp: new Date(Date.now() - 20 * 60_000).toISOString(),
      href: "/operations",
    },
    {
      id: "activity-2",
      type: "content",
      description: "Content published to LinkedIn",
      timestamp: new Date(Date.now() - 2 * 60 * 60_000).toISOString(),
    },
    {
      id: "activity-3",
      type: "campaign",
      description: "Campaign budget updated",
      timestamp: new Date(Date.now() - 5 * 60 * 60_000).toISOString(),
    },
  ],
  channelProviders: [
    { provider: "Google Ads", spend: 18200, conversions: 540, revenue: 82000, clicks: 18200, impressions: 980000 },
    { provider: "Meta Ads", spend: 23980, conversions: 703, revenue: 104420, clicks: 27478, impressions: 1476789 },
    { provider: "TikTok Ads", spend: 0, conversions: 0, revenue: 0, clicks: 0, impressions: 0 },
    { provider: "LinkedIn Ads", spend: 0, conversions: 0, revenue: 0, clicks: 0, impressions: 0 },
  ],
  previousChannelProviders: [
    { provider: "Google Ads", spend: 16800, conversions: 510, revenue: 76000, clicks: 17000, impressions: 920000 },
    { provider: "Meta Ads", spend: 22100, conversions: 680, revenue: 98000, clicks: 26000, impressions: 1400000 },
    { provider: "TikTok Ads", spend: 0, conversions: 0, revenue: 0, clicks: 0, impressions: 0 },
    { provider: "LinkedIn Ads", spend: 0, conversions: 0, revenue: 0, clicks: 0, impressions: 0 },
  ],
  healthChange: 12,
  performanceOverview: {
    spend: [
      { label: "1 Aug", value: 1200 },
      { label: "8 Aug", value: 1450 },
      { label: "15 Aug", value: 1380 },
      { label: "22 Aug", value: 1620 },
    ],
    revenue: [
      { label: "1 Aug", value: 5200 },
      { label: "8 Aug", value: 6100 },
      { label: "15 Aug", value: 5800 },
      { label: "22 Aug", value: 6900 },
    ],
    conversions: [
      { label: "1 Aug", value: 38 },
      { label: "8 Aug", value: 42 },
      { label: "15 Aug", value: 40 },
      { label: "22 Aug", value: 45 },
    ],
  },
};
