export const CRM_LEAD_STATUSES = [
  "NEW", "OPEN", "CONTACTED", "RESPONDED", "QUALIFYING", "QUALIFIED", "UNQUALIFIED",
  "NURTURING", "OPPORTUNITY_CREATED", "CUSTOMER", "LOST", "SUPPRESSED", "ARCHIVED",
] as const;

export const CRM_LIFECYCLE_STAGES = [
  "VISITOR", "LEAD", "MARKETING_QUALIFIED", "SALES_QUALIFIED", "OPPORTUNITY",
  "TRIAL", "CUSTOMER", "ACTIVE_CUSTOMER", "FORMER_CUSTOMER", "PARTNER",
] as const;

export const CRM_LEAD_SOURCE_TYPES = [
  "WEBSITE_FORM", "WEBSITE_EVENT", "SOCIAL_INBOX", "SOCIAL_LEAD_FORM",
  "ADVERTISING_LEAD_FORM", "MANUAL_ENTRY", "CSV_IMPORT", "API", "REFERRAL",
  "EVENT", "EMAIL_REPLY", "CHAT", "PARTNER", "PRODUCT_SIGNUP", "DEMO_REQUEST",
  "GRANT_INTEREST", "CAPITAL_ANALYSIS_INTEREST", "OTHER",
] as const;

export const DETERMINISTIC_IDENTITY_LINK_TYPES = [
  "AUTH_USER", "VERIFIED_EMAIL", "CONFIRMED_PHONE", "CRM_EXTERNAL_ID",
  "STRIPE_CUSTOMER", "SOCIAL_LEAD", "MARKETING_IDENTITY", "MARKETING_LEAD", "STAFF_CONFIRMED",
] as const;

export const PROHIBITED_MERGE_EVIDENCE = [
  "similar_name", "approximate_location", "device_fingerprint", "behavioural_similarity", "ai_confidence",
] as const;

export const MIN_LEADS_FOR_EXPENSIVE_FILTER = 10000;
