import { OrganisationRole } from "@prisma/client";
import { AppError } from "@/lib/errors";

export const PERMISSIONS = {
  "organisation.read": "organisation.read",
  "organisation.update": "organisation.update",
  "organisation.archive": "organisation.archive",
  "members.read": "members.read",
  "members.invite": "members.invite",
  "members.updateRole": "members.updateRole",
  "members.remove": "members.remove",
  "projects.create": "projects.create",
  "projects.read": "projects.read",
  "projects.update": "projects.update",
  "projects.archive": "projects.archive",
  "brands.create": "brands.create",
  "brands.read": "brands.read",
  "brands.update": "brands.update",
  "brands.archive": "brands.archive",
  "brandProfile.read": "brandProfile.read",
  "brandProfile.update": "brandProfile.update",
  "brandKnowledge.read": "brandKnowledge.read",
  "brandKnowledge.update": "brandKnowledge.update",
  "marketingAssets.read": "marketingAssets.read",
  "marketingAssets.update": "marketingAssets.update",
  "visualStudio.read": "visualStudio.read",
  "visualStudio.write": "visualStudio.write",
  "ai.diagnostics": "ai.diagnostics",
  "ai.usage.read": "ai.usage.read",
  "analytics.read": "analytics.read",
  "analytics.sync": "analytics.sync",
  "analytics.report": "analytics.report",
  "growth.read": "growth.read",
  "growth.generate": "growth.generate",
  "experiments.read": "experiments.read",
  "experiments.write": "experiments.write",
  "connectors.read": "connectors.read",
  "connectors.update": "connectors.update",
  "socialConnections.read": "socialConnections.read",
  "socialConnections.create": "socialConnections.create",
  "socialConnections.reconnect": "socialConnections.reconnect",
  "socialConnections.disconnect": "socialConnections.disconnect",
  "socialAccounts.assign": "socialAccounts.assign",
  "content.read": "content.read",
  "content.create": "content.create",
  "content.edit": "content.edit",
  "content.generate": "content.generate",
  "content.ideas": "content.ideas",
  "content.submitForReview": "content.submitForReview",
  "content.requestChanges": "content.requestChanges",
  "content.approve": "content.approve",
  "content.schedule": "content.schedule",
  "content.publish": "content.publish",
  "content.archive": "content.archive",
  "leads.read": "leads.read",
  "leads.write": "leads.write",
  "leads.assign": "leads.assign",
  "leads.qualify": "leads.qualify",
  "leads.export": "leads.export",
  "leads.delete": "leads.delete",
  "marketingData.read": "marketingData.read",
  "marketingData.export": "marketingData.export",
  "marketingData.manageSources": "marketingData.manageSources",
  "marketingData.runSync": "marketingData.runSync",
  "marketingData.runBackfill": "marketingData.runBackfill",
  "marketingData.viewRaw": "marketingData.viewRaw",
  "marketingData.reprocess": "marketingData.reprocess",
  "marketingData.manageQuality": "marketingData.manageQuality",
  "marketingData.manageConversions": "marketingData.manageConversions",
  "ai.analyst.read": "ai.analyst.read",
  "ai.analyst.generate": "ai.analyst.generate",
  "tracking.read": "tracking.read",
  "tracking.manage": "tracking.manage",
  "tracking.viewRaw": "tracking.viewRaw",
  "seoSites.read": "seoSites.read",
  "seoSites.create": "seoSites.create",
  "seoSites.manage": "seoSites.manage",
  "seoCrawls.run": "seoCrawls.run",
  "seoCrawls.cancel": "seoCrawls.cancel",
  "seoCrawls.export": "seoCrawls.export",
  "seoIssues.manage": "seoIssues.manage",
  "seoRawData.view": "seoRawData.view",
  "seoKeywords.read": "seoKeywords.read",
  "seoKeywords.manage": "seoKeywords.manage",
  "seoKeywords.import": "seoKeywords.import",
  "seoKeywords.export": "seoKeywords.export",
  "seoCompetitors.read": "seoCompetitors.read",
  "seoCompetitors.manage": "seoCompetitors.manage",
  "seoCompetitors.crawl": "seoCompetitors.crawl",
  "seoCompetitors.analyze": "seoCompetitors.analyze",
  "seoTopics.read": "seoTopics.read",
  "seoTopics.manage": "seoTopics.manage",
  "seoTopics.cluster": "seoTopics.cluster",
  "seoTopics.strategy": "seoTopics.strategy",
  "seoBriefs.read": "seoBriefs.read",
  "seoBriefs.manage": "seoBriefs.manage",
  "seoBriefs.generate": "seoBriefs.generate",
  "seoBriefs.approve": "seoBriefs.approve",
  "longForm.read": "longForm.read",
  "longForm.manage": "longForm.manage",
  "longForm.generate": "longForm.generate",
  "longForm.review": "longForm.review",
  "longForm.export": "longForm.export",
  "seoOnPage.read": "seoOnPage.read",
  "seoOnPage.manage": "seoOnPage.manage",
  "seoOnPage.audit": "seoOnPage.audit",
  "seoOnPage.override": "seoOnPage.override",
  "internalLinks.read": "internalLinks.read",
  "internalLinks.manage": "internalLinks.manage",
  "internalLinks.build": "internalLinks.build",
  "internalLinks.propose": "internalLinks.propose",
  "rankTracking.read": "rankTracking.read",
  "rankTracking.manage": "rankTracking.manage",
  "rankTracking.import": "rankTracking.import",
  "contentRefresh.read": "contentRefresh.read",
  "contentRefresh.manage": "contentRefresh.manage",
  "advertisingPlans.read": "advertisingPlans.read",
  "advertisingPlans.create": "advertisingPlans.create",
  "advertisingPlans.edit": "advertisingPlans.edit",
  "advertisingPlans.archive": "advertisingPlans.archive",
  "advertisingPlans.approveStrategy": "advertisingPlans.approveStrategy",
  "advertisingPlans.approveBudget": "advertisingPlans.approveBudget",
  "advertisingPlans.approveCreative": "advertisingPlans.approveCreative",
  "advertisingPlans.approveCompliance": "advertisingPlans.approveCompliance",
  "advertisingPlans.approveLaunch": "advertisingPlans.approveLaunch",
  "advertisingCreatives.read": "advertisingCreatives.read",
  "advertisingCreatives.create": "advertisingCreatives.create",
  "advertisingCreatives.edit": "advertisingCreatives.edit",
  "advertisingCreatives.generate": "advertisingCreatives.generate",
  "advertisingCreatives.review": "advertisingCreatives.review",
  "advertisingCreatives.approve": "advertisingCreatives.approve",
  "advertisingAudiences.read": "advertisingAudiences.read",
  "advertisingAudiences.create": "advertisingAudiences.create",
  "advertisingAudiences.edit": "advertisingAudiences.edit",
  "advertisingAudiences.review": "advertisingAudiences.review",
  "advertisingAudiences.approve": "advertisingAudiences.approve",
  "advertisingGoogleAds.read": "advertisingGoogleAds.read",
  "advertisingGoogleAds.connect": "advertisingGoogleAds.connect",
  "advertisingGoogleAds.draft": "advertisingGoogleAds.draft",
  "advertisingGoogleAds.validate": "advertisingGoogleAds.validate",
  "advertisingGoogleAds.launch": "advertisingGoogleAds.launch",
  "advertisingGoogleAds.manage": "advertisingGoogleAds.manage",
  "advertisingMetaAds.read": "advertisingMetaAds.read",
  "advertisingMetaAds.connect": "advertisingMetaAds.connect",
  "advertisingMetaAds.draft": "advertisingMetaAds.draft",
  "advertisingMetaAds.validate": "advertisingMetaAds.validate",
  "advertisingMetaAds.launch": "advertisingMetaAds.launch",
  "advertisingMetaAds.manage": "advertisingMetaAds.manage",
  "advertisingLinkedInAds.read": "advertisingLinkedInAds.read",
  "advertisingLinkedInAds.connect": "advertisingLinkedInAds.connect",
  "advertisingLinkedInAds.draft": "advertisingLinkedInAds.draft",
  "advertisingLinkedInAds.validate": "advertisingLinkedInAds.validate",
  "advertisingLinkedInAds.launch": "advertisingLinkedInAds.launch",
  "advertisingLinkedInAds.manage": "advertisingLinkedInAds.manage",
  "advertisingTikTokAds.read": "advertisingTikTokAds.read",
  "advertisingTikTokAds.connect": "advertisingTikTokAds.connect",
  "advertisingTikTokAds.draft": "advertisingTikTokAds.draft",
  "advertisingTikTokAds.validate": "advertisingTikTokAds.validate",
  "advertisingTikTokAds.launch": "advertisingTikTokAds.launch",
  "advertisingTikTokAds.manage": "advertisingTikTokAds.manage",
  "advertisingExperiments.read": "advertisingExperiments.read",
  "advertisingExperiments.create": "advertisingExperiments.create",
  "advertisingExperiments.edit": "advertisingExperiments.edit",
  "advertisingExperiments.analyze": "advertisingExperiments.analyze",
  "advertisingExperiments.decide": "advertisingExperiments.decide",
  "advertisingBudgets.read": "advertisingBudgets.read",
  "advertisingBudgets.manage": "advertisingBudgets.manage",
  "advertisingBudgets.request": "advertisingBudgets.request",
  "advertisingBudgets.approve": "advertisingBudgets.approve",
  "advertisingBudgets.emergency": "advertisingBudgets.emergency",
  "advertisingOptimisation.read": "advertisingOptimisation.read",
  "advertisingOptimisation.run": "advertisingOptimisation.run",
  "advertisingOptimisation.approve": "advertisingOptimisation.approve",
  "advertisingOptimisation.feedback": "advertisingOptimisation.feedback",
  "crm.read": "crm.read",
  "crm.create": "crm.create",
  "crm.edit": "crm.edit",
  "crm.archive": "crm.archive",
  "crm.export": "crm.export",
  "crm.viewSensitiveContact": "crm.viewSensitiveContact",
  "crm.manageCustomFields": "crm.manageCustomFields",
  "crm.manageDuplicates": "crm.manageDuplicates",
  "crm.mergeRecords": "crm.mergeRecords",
  "crm.assignOwner": "crm.assignOwner",
  "crm.viewRevenue": "crm.viewRevenue",
  "crm.manageConsent": "crm.manageConsent",
  "forms.read": "forms.read",
  "forms.create": "forms.create",
  "forms.edit": "forms.edit",
  "forms.publish": "forms.publish",
  "forms.archive": "forms.archive",
  "forms.viewSubmissions": "forms.viewSubmissions",
  "forms.manageRouting": "forms.manageRouting",
  "forms.reviewQuarantine": "forms.reviewQuarantine",
  "auditLogs.read": "auditLogs.read",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<OrganisationRole, Permission[]> = {
  OWNER: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS["organisation.read"],
    PERMISSIONS["organisation.update"],
    PERMISSIONS["members.read"],
    PERMISSIONS["members.invite"],
    PERMISSIONS["members.updateRole"],
    PERMISSIONS["members.remove"],
    PERMISSIONS["projects.create"],
    PERMISSIONS["projects.read"],
    PERMISSIONS["projects.update"],
    PERMISSIONS["projects.archive"],
    PERMISSIONS["brands.create"],
    PERMISSIONS["brands.read"],
    PERMISSIONS["brands.update"],
    PERMISSIONS["brands.archive"],
    PERMISSIONS["brandProfile.read"],
    PERMISSIONS["brandProfile.update"],
    PERMISSIONS["brandKnowledge.read"],
    PERMISSIONS["brandKnowledge.update"],
    PERMISSIONS["marketingAssets.read"],
    PERMISSIONS["marketingAssets.update"],
    PERMISSIONS["visualStudio.read"],
    PERMISSIONS["visualStudio.write"],
    PERMISSIONS["ai.diagnostics"],
    PERMISSIONS["ai.usage.read"],
    PERMISSIONS["analytics.read"],
    PERMISSIONS["analytics.sync"],
    PERMISSIONS["analytics.report"],
    PERMISSIONS["growth.read"],
    PERMISSIONS["growth.generate"],
    PERMISSIONS["experiments.read"],
    PERMISSIONS["experiments.write"],
    PERMISSIONS["connectors.read"],
    PERMISSIONS["connectors.update"],
    PERMISSIONS["socialConnections.read"],
    PERMISSIONS["socialConnections.create"],
    PERMISSIONS["socialConnections.reconnect"],
    PERMISSIONS["socialConnections.disconnect"],
    PERMISSIONS["socialAccounts.assign"],
    PERMISSIONS["content.read"],
    PERMISSIONS["content.create"],
    PERMISSIONS["content.edit"],
    PERMISSIONS["content.generate"],
    PERMISSIONS["content.ideas"],
    PERMISSIONS["content.submitForReview"],
    PERMISSIONS["content.requestChanges"],
    PERMISSIONS["content.approve"],
    PERMISSIONS["content.schedule"],
    PERMISSIONS["content.publish"],
    PERMISSIONS["content.archive"],
    PERMISSIONS["leads.read"],
    PERMISSIONS["leads.write"],
    PERMISSIONS["leads.assign"],
    PERMISSIONS["leads.qualify"],
    PERMISSIONS["leads.export"],
    PERMISSIONS["leads.delete"],
    PERMISSIONS["marketingData.read"],
    PERMISSIONS["marketingData.export"],
    PERMISSIONS["marketingData.manageSources"],
    PERMISSIONS["marketingData.runSync"],
    PERMISSIONS["marketingData.runBackfill"],
    PERMISSIONS["marketingData.viewRaw"],
    PERMISSIONS["marketingData.reprocess"],
    PERMISSIONS["marketingData.manageQuality"],
    PERMISSIONS["marketingData.manageConversions"],
    PERMISSIONS["ai.analyst.read"],
    PERMISSIONS["ai.analyst.generate"],
    PERMISSIONS["tracking.read"],
    PERMISSIONS["tracking.manage"],
    PERMISSIONS["tracking.viewRaw"],
    PERMISSIONS["seoSites.read"],
    PERMISSIONS["seoSites.create"],
    PERMISSIONS["seoSites.manage"],
    PERMISSIONS["seoCrawls.run"],
    PERMISSIONS["seoCrawls.cancel"],
    PERMISSIONS["seoCrawls.export"],
    PERMISSIONS["seoIssues.manage"],
    PERMISSIONS["seoRawData.view"],
    PERMISSIONS["seoKeywords.read"],
    PERMISSIONS["seoKeywords.manage"],
    PERMISSIONS["seoKeywords.import"],
    PERMISSIONS["seoKeywords.export"],
    PERMISSIONS["seoCompetitors.read"],
    PERMISSIONS["seoCompetitors.manage"],
    PERMISSIONS["seoCompetitors.crawl"],
    PERMISSIONS["seoCompetitors.analyze"],
    PERMISSIONS["seoTopics.read"],
    PERMISSIONS["seoTopics.manage"],
    PERMISSIONS["seoTopics.cluster"],
    PERMISSIONS["seoTopics.strategy"],
    PERMISSIONS["seoBriefs.read"],
    PERMISSIONS["seoBriefs.manage"],
    PERMISSIONS["seoBriefs.generate"],
    PERMISSIONS["seoBriefs.approve"],
    PERMISSIONS["longForm.read"],
    PERMISSIONS["longForm.manage"],
    PERMISSIONS["longForm.generate"],
    PERMISSIONS["longForm.review"],
    PERMISSIONS["longForm.export"],
    PERMISSIONS["seoOnPage.read"],
    PERMISSIONS["seoOnPage.manage"],
    PERMISSIONS["seoOnPage.audit"],
    PERMISSIONS["seoOnPage.override"],
    PERMISSIONS["internalLinks.read"],
    PERMISSIONS["internalLinks.manage"],
    PERMISSIONS["internalLinks.build"],
    PERMISSIONS["internalLinks.propose"],
    PERMISSIONS["rankTracking.read"],
    PERMISSIONS["rankTracking.manage"],
    PERMISSIONS["rankTracking.import"],
    PERMISSIONS["contentRefresh.read"],
    PERMISSIONS["contentRefresh.manage"],
    PERMISSIONS["advertisingPlans.read"],
    PERMISSIONS["advertisingPlans.create"],
    PERMISSIONS["advertisingPlans.edit"],
    PERMISSIONS["advertisingPlans.archive"],
    PERMISSIONS["advertisingPlans.approveStrategy"],
    PERMISSIONS["advertisingPlans.approveBudget"],
    PERMISSIONS["advertisingPlans.approveCreative"],
    PERMISSIONS["advertisingPlans.approveCompliance"],
    PERMISSIONS["advertisingPlans.approveLaunch"],
    PERMISSIONS["advertisingCreatives.read"],
    PERMISSIONS["advertisingCreatives.create"],
    PERMISSIONS["advertisingCreatives.edit"],
    PERMISSIONS["advertisingCreatives.generate"],
    PERMISSIONS["advertisingCreatives.review"],
    PERMISSIONS["advertisingCreatives.approve"],
    PERMISSIONS["advertisingAudiences.read"],
    PERMISSIONS["advertisingAudiences.create"],
    PERMISSIONS["advertisingAudiences.edit"],
    PERMISSIONS["advertisingAudiences.review"],
    PERMISSIONS["advertisingAudiences.approve"],
    PERMISSIONS["advertisingGoogleAds.read"],
    PERMISSIONS["advertisingGoogleAds.connect"],
    PERMISSIONS["advertisingGoogleAds.draft"],
    PERMISSIONS["advertisingGoogleAds.validate"],
    PERMISSIONS["advertisingGoogleAds.launch"],
    PERMISSIONS["advertisingGoogleAds.manage"],
    PERMISSIONS["advertisingMetaAds.read"],
    PERMISSIONS["advertisingMetaAds.connect"],
    PERMISSIONS["advertisingMetaAds.draft"],
    PERMISSIONS["advertisingMetaAds.validate"],
    PERMISSIONS["advertisingMetaAds.launch"],
    PERMISSIONS["advertisingMetaAds.manage"],
    PERMISSIONS["advertisingLinkedInAds.read"],
    PERMISSIONS["advertisingLinkedInAds.connect"],
    PERMISSIONS["advertisingLinkedInAds.draft"],
    PERMISSIONS["advertisingLinkedInAds.validate"],
    PERMISSIONS["advertisingLinkedInAds.launch"],
    PERMISSIONS["advertisingLinkedInAds.manage"],
    PERMISSIONS["advertisingTikTokAds.read"],
    PERMISSIONS["advertisingTikTokAds.connect"],
    PERMISSIONS["advertisingTikTokAds.draft"],
    PERMISSIONS["advertisingTikTokAds.validate"],
    PERMISSIONS["advertisingTikTokAds.launch"],
    PERMISSIONS["advertisingTikTokAds.manage"],
    PERMISSIONS["advertisingExperiments.read"],
    PERMISSIONS["advertisingExperiments.create"],
    PERMISSIONS["advertisingExperiments.edit"],
    PERMISSIONS["advertisingExperiments.analyze"],
    PERMISSIONS["advertisingExperiments.decide"],
    PERMISSIONS["advertisingBudgets.read"],
    PERMISSIONS["advertisingBudgets.manage"],
    PERMISSIONS["advertisingBudgets.request"],
    PERMISSIONS["advertisingBudgets.approve"],
    PERMISSIONS["advertisingBudgets.emergency"],
    PERMISSIONS["advertisingOptimisation.read"],
    PERMISSIONS["advertisingOptimisation.run"],
    PERMISSIONS["advertisingOptimisation.approve"],
    PERMISSIONS["advertisingOptimisation.feedback"],
    PERMISSIONS["crm.read"],
    PERMISSIONS["crm.create"],
    PERMISSIONS["crm.edit"],
    PERMISSIONS["crm.archive"],
    PERMISSIONS["crm.export"],
    PERMISSIONS["crm.viewSensitiveContact"],
    PERMISSIONS["crm.manageCustomFields"],
    PERMISSIONS["crm.manageDuplicates"],
    PERMISSIONS["crm.mergeRecords"],
    PERMISSIONS["crm.assignOwner"],
    PERMISSIONS["crm.viewRevenue"],
    PERMISSIONS["crm.manageConsent"],
    PERMISSIONS["forms.read"],
    PERMISSIONS["forms.create"],
    PERMISSIONS["forms.edit"],
    PERMISSIONS["forms.publish"],
    PERMISSIONS["forms.archive"],
    PERMISSIONS["forms.viewSubmissions"],
    PERMISSIONS["forms.manageRouting"],
    PERMISSIONS["forms.reviewQuarantine"],
    PERMISSIONS["auditLogs.read"],
  ],
  MARKETER: [
    PERMISSIONS["organisation.read"],
    PERMISSIONS["members.read"],
    PERMISSIONS["projects.create"],
    PERMISSIONS["projects.read"],
    PERMISSIONS["projects.update"],
    PERMISSIONS["brands.create"],
    PERMISSIONS["brands.read"],
    PERMISSIONS["brands.update"],
    PERMISSIONS["brandProfile.read"],
    PERMISSIONS["brandProfile.update"],
    PERMISSIONS["brandKnowledge.read"],
    PERMISSIONS["brandKnowledge.update"],
    PERMISSIONS["marketingAssets.read"],
    PERMISSIONS["marketingAssets.update"],
    PERMISSIONS["analytics.read"],
    PERMISSIONS["analytics.report"],
    PERMISSIONS["growth.read"],
    PERMISSIONS["growth.generate"],
    PERMISSIONS["experiments.read"],
    PERMISSIONS["experiments.write"],
    PERMISSIONS["visualStudio.read"],
    PERMISSIONS["visualStudio.write"],
    PERMISSIONS["connectors.read"],
    PERMISSIONS["connectors.update"],
    PERMISSIONS["socialConnections.read"],
    PERMISSIONS["socialConnections.create"],
    PERMISSIONS["socialConnections.reconnect"],
    PERMISSIONS["socialConnections.disconnect"],
    PERMISSIONS["socialAccounts.assign"],
    PERMISSIONS["content.read"],
    PERMISSIONS["content.create"],
    PERMISSIONS["content.edit"],
    PERMISSIONS["content.generate"],
    PERMISSIONS["content.ideas"],
    PERMISSIONS["content.submitForReview"],
    PERMISSIONS["content.archive"],
    PERMISSIONS["leads.read"],
    PERMISSIONS["leads.write"],
    PERMISSIONS["leads.assign"],
    PERMISSIONS["leads.qualify"],
    PERMISSIONS["leads.export"],
    PERMISSIONS["marketingData.read"],
    PERMISSIONS["marketingData.runSync"],
    PERMISSIONS["marketingData.manageConversions"],
    PERMISSIONS["ai.analyst.read"],
    PERMISSIONS["ai.analyst.generate"],
    PERMISSIONS["tracking.read"],
    PERMISSIONS["seoSites.read"],
    PERMISSIONS["seoSites.create"],
    PERMISSIONS["seoCrawls.run"],
    PERMISSIONS["seoCrawls.export"],
    PERMISSIONS["seoIssues.manage"],
    PERMISSIONS["seoKeywords.read"],
    PERMISSIONS["seoKeywords.manage"],
    PERMISSIONS["seoKeywords.import"],
    PERMISSIONS["seoCompetitors.read"],
    PERMISSIONS["seoCompetitors.manage"],
    PERMISSIONS["seoCompetitors.crawl"],
    PERMISSIONS["seoCompetitors.analyze"],
    PERMISSIONS["seoTopics.read"],
    PERMISSIONS["seoTopics.manage"],
    PERMISSIONS["seoTopics.cluster"],
    PERMISSIONS["seoTopics.strategy"],
    PERMISSIONS["seoBriefs.read"],
    PERMISSIONS["seoBriefs.manage"],
    PERMISSIONS["seoBriefs.generate"],
    PERMISSIONS["longForm.read"],
    PERMISSIONS["longForm.manage"],
    PERMISSIONS["longForm.generate"],
    PERMISSIONS["longForm.export"],
    PERMISSIONS["seoOnPage.read"],
    PERMISSIONS["seoOnPage.manage"],
    PERMISSIONS["seoOnPage.audit"],
    PERMISSIONS["internalLinks.read"],
    PERMISSIONS["internalLinks.manage"],
    PERMISSIONS["internalLinks.build"],
    PERMISSIONS["rankTracking.read"],
    PERMISSIONS["rankTracking.manage"],
    PERMISSIONS["rankTracking.import"],
    PERMISSIONS["contentRefresh.read"],
    PERMISSIONS["contentRefresh.manage"],
    PERMISSIONS["advertisingPlans.read"],
    PERMISSIONS["advertisingPlans.create"],
    PERMISSIONS["advertisingPlans.edit"],
    PERMISSIONS["advertisingCreatives.read"],
    PERMISSIONS["advertisingCreatives.create"],
    PERMISSIONS["advertisingCreatives.edit"],
    PERMISSIONS["advertisingCreatives.generate"],
    PERMISSIONS["advertisingAudiences.read"],
    PERMISSIONS["advertisingAudiences.create"],
    PERMISSIONS["advertisingAudiences.edit"],
    PERMISSIONS["advertisingGoogleAds.read"],
    PERMISSIONS["advertisingGoogleAds.connect"],
    PERMISSIONS["advertisingGoogleAds.draft"],
    PERMISSIONS["advertisingGoogleAds.validate"],
    PERMISSIONS["advertisingMetaAds.read"],
    PERMISSIONS["advertisingMetaAds.connect"],
    PERMISSIONS["advertisingMetaAds.draft"],
    PERMISSIONS["advertisingMetaAds.validate"],
    PERMISSIONS["advertisingLinkedInAds.read"],
    PERMISSIONS["advertisingLinkedInAds.connect"],
    PERMISSIONS["advertisingLinkedInAds.draft"],
    PERMISSIONS["advertisingLinkedInAds.validate"],
    PERMISSIONS["advertisingTikTokAds.read"],
    PERMISSIONS["advertisingTikTokAds.connect"],
    PERMISSIONS["advertisingTikTokAds.draft"],
    PERMISSIONS["advertisingTikTokAds.validate"],
    PERMISSIONS["advertisingExperiments.read"],
    PERMISSIONS["advertisingExperiments.create"],
    PERMISSIONS["advertisingExperiments.edit"],
    PERMISSIONS["advertisingExperiments.analyze"],
    PERMISSIONS["advertisingBudgets.read"],
    PERMISSIONS["advertisingBudgets.manage"],
    PERMISSIONS["advertisingBudgets.request"],
    PERMISSIONS["advertisingOptimisation.read"],
    PERMISSIONS["advertisingOptimisation.run"],
    PERMISSIONS["advertisingOptimisation.feedback"],
    PERMISSIONS["crm.read"],
    PERMISSIONS["crm.create"],
    PERMISSIONS["crm.edit"],
    PERMISSIONS["crm.export"],
    PERMISSIONS["crm.assignOwner"],
    PERMISSIONS["crm.manageDuplicates"],
    PERMISSIONS["forms.read"],
    PERMISSIONS["forms.create"],
    PERMISSIONS["forms.edit"],
    PERMISSIONS["forms.publish"],
    PERMISSIONS["forms.viewSubmissions"],
    PERMISSIONS["forms.manageRouting"],
  ],
  ANALYST: [
    PERMISSIONS["organisation.read"],
    PERMISSIONS["members.read"],
    PERMISSIONS["projects.read"],
    PERMISSIONS["brands.read"],
    PERMISSIONS["brandProfile.read"],
    PERMISSIONS["brandKnowledge.read"],
    PERMISSIONS["marketingAssets.read"],
    PERMISSIONS["visualStudio.read"],
    PERMISSIONS["ai.usage.read"],
    PERMISSIONS["analytics.read"],
    PERMISSIONS["analytics.report"],
    PERMISSIONS["growth.read"],
    PERMISSIONS["experiments.read"],
    PERMISSIONS["connectors.read"],
    PERMISSIONS["socialConnections.read"],
    PERMISSIONS["content.read"],
    PERMISSIONS["leads.read"],
    PERMISSIONS["leads.export"],
    PERMISSIONS["marketingData.read"],
    PERMISSIONS["marketingData.export"],
    PERMISSIONS["marketingData.manageQuality"],
    PERMISSIONS["ai.analyst.read"],
    PERMISSIONS["tracking.read"],
    PERMISSIONS["seoSites.read"],
    PERMISSIONS["seoCrawls.export"],
    PERMISSIONS["seoKeywords.read"],
    PERMISSIONS["seoKeywords.export"],
    PERMISSIONS["seoCompetitors.read"],
    PERMISSIONS["seoCompetitors.analyze"],
    PERMISSIONS["seoTopics.read"],
    PERMISSIONS["seoBriefs.read"],
    PERMISSIONS["longForm.read"],
    PERMISSIONS["seoOnPage.read"],
    PERMISSIONS["internalLinks.read"],
    PERMISSIONS["rankTracking.read"],
    PERMISSIONS["contentRefresh.read"],
    PERMISSIONS["advertisingPlans.read"],
    PERMISSIONS["advertisingCreatives.read"],
    PERMISSIONS["advertisingAudiences.read"],
    PERMISSIONS["advertisingGoogleAds.read"],
    PERMISSIONS["advertisingMetaAds.read"],
    PERMISSIONS["advertisingLinkedInAds.read"],
    PERMISSIONS["advertisingTikTokAds.read"],
    PERMISSIONS["advertisingExperiments.read"],
    PERMISSIONS["advertisingBudgets.read"],
    PERMISSIONS["advertisingOptimisation.read"],
    PERMISSIONS["crm.read"],
    PERMISSIONS["crm.export"],
    PERMISSIONS["forms.read"],
    PERMISSIONS["forms.viewSubmissions"],
    PERMISSIONS["auditLogs.read"],
  ],
  VIEWER: [
    PERMISSIONS["organisation.read"],
    PERMISSIONS["members.read"],
    PERMISSIONS["projects.read"],
    PERMISSIONS["brands.read"],
    PERMISSIONS["brandProfile.read"],
    PERMISSIONS["brandKnowledge.read"],
    PERMISSIONS["marketingAssets.read"],
    PERMISSIONS["visualStudio.read"],
    PERMISSIONS["connectors.read"],
    PERMISSIONS["socialConnections.read"],
    PERMISSIONS["content.read"],
    PERMISSIONS["leads.read"],
    PERMISSIONS["marketingData.read"],
    PERMISSIONS["ai.analyst.read"],
    PERMISSIONS["tracking.read"],
    PERMISSIONS["seoSites.read"],
    PERMISSIONS["seoKeywords.read"],
    PERMISSIONS["seoCompetitors.read"],
    PERMISSIONS["seoTopics.read"],
    PERMISSIONS["seoBriefs.read"],
    PERMISSIONS["longForm.read"],
    PERMISSIONS["seoOnPage.read"],
    PERMISSIONS["internalLinks.read"],
    PERMISSIONS["rankTracking.read"],
    PERMISSIONS["contentRefresh.read"],
    PERMISSIONS["advertisingPlans.read"],
    PERMISSIONS["advertisingCreatives.read"],
    PERMISSIONS["advertisingAudiences.read"],
    PERMISSIONS["advertisingGoogleAds.read"],
    PERMISSIONS["advertisingMetaAds.read"],
    PERMISSIONS["advertisingLinkedInAds.read"],
    PERMISSIONS["advertisingTikTokAds.read"],
    PERMISSIONS["advertisingExperiments.read"],
    PERMISSIONS["advertisingBudgets.read"],
    PERMISSIONS["advertisingOptimisation.read"],
    PERMISSIONS["crm.read"],
    PERMISSIONS["forms.read"],
    PERMISSIONS["experiments.read"],
  ],
};

export function hasPermission(role: OrganisationRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}

export function requirePermission(role: OrganisationRole, permission: Permission): void {
  if (!hasPermission(role, permission)) {
    throw new AppError("FORBIDDEN", `Missing permission: ${permission}`);
  }
}

export function canManageMember(
  actorRole: OrganisationRole,
  targetRole: OrganisationRole,
): boolean {
  if (!hasPermission(actorRole, PERMISSIONS["members.updateRole"])) {
    return false;
  }

  if (targetRole === OrganisationRole.OWNER && actorRole !== OrganisationRole.OWNER) {
    return false;
  }

  return true;
}

export function canChangeRole(
  actorRole: OrganisationRole,
  fromRole: OrganisationRole,
  toRole: OrganisationRole,
): boolean {
  if (!canManageMember(actorRole, fromRole)) {
    return false;
  }

  if (toRole === OrganisationRole.OWNER && actorRole !== OrganisationRole.OWNER) {
    return false;
  }

  if (fromRole === OrganisationRole.OWNER && actorRole !== OrganisationRole.OWNER) {
    return false;
  }

  return true;
}

export function getRolePermissions(role: OrganisationRole): Permission[] {
  return ROLE_PERMISSIONS[role];
}
