export const CONNECTOR_OAUTH_STATE_TTL_MS = 10 * 60 * 1000;
export const CONNECTOR_SYNC_MAX_RETRIES = 3;
export const CONNECTOR_SYNC_BASE_DELAY_MS = 1_000;
export const CONNECTOR_SYNC_MAX_DELAY_MS = 30_000;
export const CONNECTOR_RATE_LIMIT_DEFAULT_RETRY_AFTER_MS = 60_000;
