export const ANALYTICS_METRIC_KEYS = {
  IMPRESSIONS: "impressions",
  REACH: "reach",
  CLICKS: "clicks",
  SESSIONS: "sessions",
  ENGAGEMENT: "engagement",
  LEADS: "leads",
  CONVERSIONS: "conversions",
  SPEND: "spend",
  REVENUE: "revenue",
  CTR: "ctr",
  CPC: "cpc",
  CPM: "cpm",
  CPL: "cpl",
  CPA: "cpa",
  ROAS: "roas",
  CONVERSION_RATE: "conversion_rate",
} as const;

export type AnalyticsMetricKey = (typeof ANALYTICS_METRIC_KEYS)[keyof typeof ANALYTICS_METRIC_KEYS];

export const BASE_METRIC_KEYS = [
  ANALYTICS_METRIC_KEYS.IMPRESSIONS,
  ANALYTICS_METRIC_KEYS.REACH,
  ANALYTICS_METRIC_KEYS.CLICKS,
  ANALYTICS_METRIC_KEYS.SESSIONS,
  ANALYTICS_METRIC_KEYS.ENGAGEMENT,
  ANALYTICS_METRIC_KEYS.LEADS,
  ANALYTICS_METRIC_KEYS.CONVERSIONS,
  ANALYTICS_METRIC_KEYS.SPEND,
  ANALYTICS_METRIC_KEYS.REVENUE,
] as const;

export const DERIVED_METRIC_KEYS = [
  ANALYTICS_METRIC_KEYS.CTR,
  ANALYTICS_METRIC_KEYS.CPC,
  ANALYTICS_METRIC_KEYS.CPM,
  ANALYTICS_METRIC_KEYS.CPL,
  ANALYTICS_METRIC_KEYS.CPA,
  ANALYTICS_METRIC_KEYS.ROAS,
  ANALYTICS_METRIC_KEYS.CONVERSION_RATE,
] as const;

export const ALL_METRIC_KEYS = [...BASE_METRIC_KEYS, ...DERIVED_METRIC_KEYS] as const;

export const CURRENCY_METRIC_KEYS = new Set<string>([
  ANALYTICS_METRIC_KEYS.SPEND,
  ANALYTICS_METRIC_KEYS.REVENUE,
  ANALYTICS_METRIC_KEYS.CPC,
  ANALYTICS_METRIC_KEYS.CPM,
  ANALYTICS_METRIC_KEYS.CPL,
  ANALYTICS_METRIC_KEYS.CPA,
]);

export type AnalyticsFreshnessState = "FRESH" | "STALE" | "CRITICAL" | "UNKNOWN";

export type AnalyticsDataCoverageState = "NO_DATA" | "PARTIAL" | "COMPLETE";

export const ANALYTICS_DEFAULT_FRESHNESS_INTERVAL_MINUTES = 24 * 60;

export const ANALYTICS_FRESHNESS_STALE_MULTIPLIER = 1.5;
export const ANALYTICS_FRESHNESS_CRITICAL_MULTIPLIER = 3;
