import type { ContentIntelligenceWorkspace } from "@/lib/content-intelligence/types";

export const CONTENT_INTELLIGENCE_VISUAL_PREVIEW_FIXTURE: ContentIntelligenceWorkspace = {
  hasBrandContext: true,
  dateRange: {
    label: "Last 30 days",
    from: "2026-07-25T00:00:00.000Z",
    to: "2026-08-24T00:00:00.000Z",
  },
  freshness: { label: "Updated 4 minutes ago", state: "fresh" },
  kpis: [
    { label: "Content created", value: "24", comparisonLabel: "Last 30 days", state: "normal" },
    { label: "Awaiting approval", value: "3", state: "partial" },
    { label: "Scheduled", value: "5", state: "normal" },
    { label: "Published", value: "12", state: "normal" },
    { label: "Winning content", value: "2", state: "normal" },
  ],
  priorities: [
    {
      id: "p1",
      title: "3 items awaiting approval",
      urgency: "high",
      context: "LinkedIn carousel and two X posts need review before publishing.",
      action: { label: "Review workflow", href: "/content/studio/workflow" },
    },
    {
      id: "p2",
      title: "Winning content ready to repurpose",
      urgency: "normal",
      context: "SEIS eligibility post performed 2.1× above account median.",
      action: { label: "Create brief", href: "/content/studio/create?source=winning" },
    },
    {
      id: "p3",
      title: "Brand context incomplete",
      urgency: "normal",
      context: "Missing target persona and core proof points.",
      action: { label: "Complete brand profile", href: "/brands/brand-preview/knowledge" },
    },
  ],
  nextRecommendation: {
    id: "next-1",
    title: "Recommended next content",
    topic: "5 reasons SEIS applications get delayed",
    format: "Educational LinkedIn carousel",
    channels: ["LINKEDIN"],
    why: [
      "Funding-process content performs 1.8× above your median",
      "No LinkedIn post is scheduled for the next 4 days",
      "Current campaign targets startup founders",
    ],
    evidence: [
      { label: "Theme lift", value: "1.8×" },
      { label: "Channel gap", value: "LinkedIn" },
      { label: "Campaign", value: "Q3 Founder Outreach" },
    ],
    evidenceStrength: "strong",
    action: { label: "Create brief", href: "/content/studio/create" },
  },
  opportunities: [
    {
      id: "opp-1",
      source: "winning_content",
      title: "Repurpose winning content",
      finding: "SEIS eligibility explainer outperformed on LinkedIn",
      evidence: [
        { label: "Lift", value: "2.1× engagement" },
        { label: "Sample", value: "18 comparable posts" },
      ],
      whyItMatters: "High-performing content can extend reach through repurposing.",
      recommendedContent: "Follow-up carousel on application workflow",
      recommendedChannels: ["LINKEDIN", "X"],
      evidenceStrength: "strong",
      action: { label: "Create brief", href: "/content/studio/create?source=winning" },
    },
  ],
  strategy: {
    primaryObjective: "lead_generation",
    funnelStage: "consideration",
    targetAudienceIds: ["aud-1"],
    targetAudienceLabels: ["Startup founders", "Finance leads"],
    offerIds: ["offer-1"],
    offerLabels: ["Cresco Grants Advisory"],
    contentPillars: ["funding_opportunities", "product_education", "founder_insights"],
    primaryChannels: ["LINKEDIN", "X"],
    secondaryChannels: ["INSTAGRAM", "YOUTUBE"],
    publishingCadence: "3–5 posts per week",
    keyMessages: ["Simplify grant applications", "Expert funding guidance"],
    ctaStrategy: "Drive eligibility checks",
    constraints: ["No guaranteed funding claims"],
    complianceNotes: ["Include risk disclaimer where required"],
    successMetrics: ["Reach", "Engagement rate", "Profile visits"],
    narrative: "Build authority with founders through educational funding content.",
  },
  themes: [
    {
      key: "funding_opportunities",
      label: "Funding opportunities",
      description: "Grants and SEIS/EIS guidance",
      objective: "lead_generation",
      preferredAudiences: ["Startup founders"],
      preferredChannels: ["LINKEDIN"],
      active: true,
      performanceSummary: {
        reach: 38400,
        engagement: 1920,
        posts: 8,
        classification: "winning",
      },
    },
    {
      key: "product_education",
      label: "Product education",
      description: "Product value and use cases",
      objective: "education",
      preferredAudiences: ["Finance leads"],
      preferredChannels: ["LINKEDIN", "YOUTUBE"],
      active: true,
      performanceSummary: {
        reach: 22100,
        engagement: 880,
        posts: 6,
        classification: "strong",
      },
    },
  ],
  themePerformance: [
    {
      theme: "funding_opportunities",
      label: "Funding opportunities",
      reach: 38400,
      engagement: 1920,
      clicks: 340,
      posts: 8,
      classification: "winning",
    },
    {
      theme: "product_education",
      label: "Product education",
      reach: 22100,
      engagement: 880,
      clicks: 120,
      posts: 6,
      classification: "strong",
    },
  ],
  learnings: [
    {
      id: "l1",
      pattern: "Strong hook pattern",
      observation: "Posts beginning with a concrete funding number perform 2.1× above baseline.",
      evidenceStrength: "strong",
      dimension: "hook",
      sampleSize: 18,
      disclaimer: "Based on observed account performance. Not causal evidence.",
    },
    {
      id: "l2",
      pattern: "Format signal",
      observation: "Educational carousels outperform static promotional posts on LinkedIn.",
      evidenceStrength: "moderate",
      dimension: "format",
      sampleSize: 12,
      disclaimer: "Based on observed account performance. Not causal evidence.",
    },
  ],
  pipeline: [
    {
      id: "c1",
      title: "SEIS application delays carousel",
      status: "IN REVIEW",
      contentPillar: "funding_opportunities",
      campaignLabel: "Q3 Founder Outreach",
      channel: "LINKEDIN",
      dueAt: "2026-08-26T00:00:00.000Z",
      href: "/content/studio/c1",
    },
    {
      id: "c2",
      title: "Founder funding myths thread",
      status: "DRAFT",
      contentPillar: "founder_insights",
      campaignLabel: null,
      channel: "X",
      dueAt: null,
      href: "/content/studio/c2",
    },
  ],
  topPerforming: [
    {
      id: "w1",
      title: "SEIS eligibility explained",
      channel: "LinkedIn",
      metricLabel: "Engagement rate",
      metricValue: "4.2%",
      classification: "winning",
      href: "/content/studio/w1",
    },
  ],
  weakPerforming: [
    {
      id: "w2",
      title: "Generic product promo",
      channel: "LinkedIn",
      metricLabel: "Engagement rate",
      metricValue: "0.8%",
      classification: "weak",
      href: "/content/studio/w2",
    },
  ],
  brandReadiness: {
    overallScore: 72,
    complete: false,
    missing: [
      { category: "Audience", label: "Target persona" },
      { category: "Messaging", label: "Core proof points" },
    ],
    impactMessage:
      "Cresco can still generate drafts, but brand alignment may be weaker until key fields are completed.",
    completeBrandHref: "/brands/brand-preview/knowledge",
  },
  upcomingPublications: [
    {
      id: "s1",
      title: "Grant deadline reminder",
      channel: "LinkedIn",
      scheduledFor: "2026-08-26T09:00:00.000Z",
      status: "SCHEDULED",
    },
  ],
};
