/**
 * Development-only fixture for Organic Growth visual QA.
 * Never imported by production API routes or services.
 */
import type { OrganicGrowthEngineData } from "@/lib/organic-growth/types";
import { ORGANIC_PROVIDER_REGISTRY } from "@/lib/organic-growth/providers";

export const ORGANIC_GROWTH_VISUAL_PREVIEW_FIXTURE: OrganicGrowthEngineData = {
  hasBrandContext: true,
  dateRange: {
    label: "Last 30 days",
    comparisonLabel: "vs previous 30 days",
    from: "2026-07-25T00:00:00.000Z",
    to: "2026-08-24T00:00:00.000Z",
  },
  freshness: { label: "Updated 8 min ago", state: "fresh" },
  coverage: "4 of 9 core channels connected",
  partialCoverageNote: "Threads and Pinterest are on the provider roadmap.",
  primaryCta: { label: "Create content", href: "/content/studio/new" },
  executiveKpis: [
    {
      label: "Organic Reach",
      value: "284.2K",
      change: 12.4,
      comparisonLabel: "vs previous 30 days",
      state: "normal",
    },
    {
      label: "Engagements",
      value: "18,420",
      change: 8.1,
      comparisonLabel: "vs previous 30 days",
      state: "normal",
    },
    {
      label: "Follower Growth",
      value: "+1,240",
      change: 6.2,
      comparisonLabel: "vs previous 30 days",
      state: "normal",
    },
    {
      label: "Website Traffic",
      value: "—",
      change: null,
      comparisonLabel: "vs previous 30 days",
      state: "unavailable",
      stateMessage: "Connect analytics to track organic social referred sessions.",
    },
    {
      label: "Organic Conversions",
      value: "—",
      change: null,
      comparisonLabel: "vs previous 30 days",
      state: "unavailable",
      stateMessage: "Conversion attribution for organic social is not yet configured.",
    },
    {
      label: "Organic Growth Score",
      value: "71 / 100",
      change: null,
      comparisonLabel: "vs previous 30 days",
      state: "normal",
    },
  ],
  growthScore: {
    total: 71,
    maxTotal: 100,
    dimensions: [
      {
        key: "publishing_consistency",
        label: "Publishing consistency",
        score: 12,
        maxScore: 15,
        explanation: "3 day(s) without scheduled content in the near term.",
        recommendedImprovement: "Schedule at least 2 additional posts this week to maintain cadence.",
      },
      {
        key: "engagement_quality",
        label: "Engagement quality",
        score: 11,
        maxScore: 15,
        explanation: "Engagement rate is 4.20% for the selected period.",
      },
      {
        key: "audience_growth",
        label: "Audience growth",
        score: 10,
        maxScore: 15,
        explanation: "Net follower growth rate is +6.2%.",
      },
      {
        key: "content_diversity",
        label: "Content diversity",
        score: 6,
        maxScore: 10,
        explanation: "3 distinct format(s) used across 18 published item(s).",
      },
      {
        key: "channel_coverage",
        label: "Channel coverage",
        score: 4,
        maxScore: 10,
        explanation: "4 of 9 core channels connected.",
      },
      {
        key: "conversion_contribution",
        label: "Conversion contribution",
        score: 0,
        maxScore: 10,
        explanation: "Conversion attribution for organic social is not yet configured.",
        unavailable: true,
      },
      {
        key: "community_engagement",
        label: "Community engagement",
        score: 0,
        maxScore: 10,
        explanation: "Community intelligence sources are not connected.",
        unavailable: true,
      },
      {
        key: "experiment_velocity",
        label: "Experiment velocity",
        score: 0,
        maxScore: 10,
        explanation: "No organic experiments recorded for this brand.",
        unavailable: true,
      },
    ],
  },
  accounts: [
    {
      id: "LINKEDIN",
      provider: "LinkedIn",
      providerKey: "LINKEDIN",
      displayName: "Cresco Grants",
      handle: "@cresco-grants",
      connectionState: "healthy",
      connectionLabel: "Connected",
      lastSyncAt: "8 min ago",
      freshness: "fresh",
      freshnessLabel: "Updated 8 min ago",
      followers: 12400,
      followerGrowth: 820,
      followerGrowthRate: 8.2,
      reach: 98400,
      engagementRate: 4.7,
      publishingStatus: "active",
      scheduledCount: 3,
      actions: {
        performanceHref: "/organic-social/content",
        createHref: "/content/studio/new",
        queueHref: "/organic-social/publishing",
        connectHref: "/organic-social/accounts",
      },
    },
    {
      id: "X",
      provider: "X",
      providerKey: "X",
      displayName: "Cresco AI",
      handle: "@crescoai",
      connectionState: "stale",
      connectionLabel: "Sync delayed",
      lastSyncAt: "2 days ago",
      freshness: "stale",
      freshnessLabel: "Sync delayed (2d ago)",
      followers: 3200,
      followerGrowth: 120,
      followerGrowthRate: 3.9,
      reach: 41200,
      engagementRate: 2.1,
      publishingStatus: "idle",
      scheduledCount: 0,
      actions: {
        performanceHref: "/organic-social/content",
        createHref: "/content/studio/new",
        queueHref: "/organic-social/publishing",
        connectHref: "/organic-social/accounts",
      },
    },
  ],
  priorities: [
    {
      id: "organic-priority-0",
      title: "Publishing gap detected",
      urgency: "high",
      context: "No LinkedIn content scheduled for the next 5 days.",
      action: { label: "Schedule content", href: "/calendar" },
    },
    {
      id: "organic-priority-1",
      title: "X sync delayed",
      urgency: "high",
      context: "Account analytics may be incomplete until sync completes.",
      action: { label: "Reconnect", href: "/social/connections" },
    },
  ],
  topOpportunity: {
    id: "repurpose-preview-1",
    type: "winning_repurpose",
    title: "Winning content ready to repurpose",
    finding:
      '"5 UK grants startups should apply for this month" on LinkedIn — 2.8× account median engagement · 1.9× profile visits.',
    evidence: [
      { label: "Engagement lift", value: "2.8× baseline" },
      { label: "Confidence", value: "medium" },
    ],
    confidence: "medium",
    potentialImpact: "Extend proven creative across additional channels",
    action: { label: "Create variants", href: "/content/studio/preview-1?action=variants" },
  },
  winningContent: [
    {
      id: "preview-winner-1",
      title: "5 UK grants startups should apply for this month",
      channel: "LinkedIn",
      format: "TEXT_POST",
      publishedAt: "2026-08-18T09:00:00.000Z",
      reach: 18400,
      engagements: 1240,
      engagementRate: 0.067,
      profileVisits: 420,
      clicks: 186,
      baselineEngagementRate: 0.024,
      engagementLift: 2.8,
      profileVisitLift: 1.9,
      clickLift: 3.1,
      confidence: "medium",
      evidenceStrength: "moderate",
      evidenceLabel: "2.8× account median engagement · 1.9× profile visits · 3.1× website clicks",
      baselineDescription: "Compared with your account median for last 30 days",
      sampleSize: 18,
      comparisonWindow: "last 30 days",
      disclaimer: "Performance signal based on observed account data — not causal evidence.",
      theme: "Grants",
      actions: [
        { label: "Repurpose", href: "/content/studio/preview-1?action=repurpose" },
        { label: "Create variants", href: "/content/studio/preview-1?action=variants" },
        { label: "Create experiment", href: "/growth/experiments/new?source=preview-winner-1" },
      ],
    },
  ],
  opportunities: [
    {
      id: "repurpose-preview-1",
      type: "winning_repurpose",
      title: "Winning content ready to repurpose",
      finding:
        '"5 UK grants startups should apply for this month" on LinkedIn — 2.8× account median engagement.',
      evidence: [
        { label: "Engagement lift", value: "2.8× baseline" },
        { label: "Confidence", value: "medium" },
      ],
      confidence: "medium",
      potentialImpact: "Extend proven creative across additional channels",
      action: { label: "Create variants", href: "/content/studio/preview-1?action=variants" },
    },
    {
      id: "consistency-linkedin",
      type: "consistency_gap",
      title: "Publishing consistency gap",
      finding: "No LinkedIn content scheduled for the next 5 days.",
      evidence: [{ label: "Channel", value: "LinkedIn" }],
      confidence: "medium",
      potentialImpact: "Maintain reach momentum with consistent publishing",
      action: { label: "Open calendar", href: "/calendar" },
    },
    {
      id: "best-time-linkedin",
      type: "best_time",
      title: "High-performing window on LinkedIn",
      finding: "Tuesday 08:00–10:00 shows 3.2× baseline engagement.",
      evidence: [
        { label: "Sample size", value: "14" },
        { label: "Lift", value: "3.2×" },
      ],
      confidence: "medium",
      potentialImpact: "Schedule during observed high-engagement windows",
      action: { label: "Schedule content", href: "/organic-social/publishing" },
    },
  ],
  contentPerformance: [
    {
      id: "preview-winner-1",
      title: "5 UK grants startups should apply for this month",
      channel: "LinkedIn",
      format: "TEXT_POST",
      theme: "Grants",
      campaign: null,
      publishedAt: "2026-08-18T09:00:00.000Z",
      reach: 18400,
      impressions: 22100,
      engagements: 1240,
      engagementRate: 6.7,
      clicks: 186,
      profileVisits: 420,
      followsGained: 42,
      conversionsInfluenced: null,
      status: "PUBLISHED",
      sourceContentId: null,
      isWinning: true,
    },
    {
      id: "preview-content-2",
      title: "Founder story: why we built Cresco",
      channel: "X",
      format: "THREAD",
      theme: "Founder story",
      campaign: null,
      publishedAt: "2026-08-12T14:30:00.000Z",
      reach: 8200,
      impressions: 9100,
      engagements: 312,
      engagementRate: 3.8,
      clicks: 48,
      profileVisits: 96,
      followsGained: 18,
      conversionsInfluenced: null,
      status: "PUBLISHED",
      sourceContentId: null,
      isWinning: false,
    },
  ],
  publishingQueue: [
    {
      id: "pub-preview-1",
      title: "SEIS eligibility checklist for founders",
      preview: "A practical breakdown of SEIS requirements…",
      channel: "LinkedIn",
      accountName: "Cresco Grants",
      scheduledAt: "2026-08-26T08:00:00.000Z",
      campaign: null,
      status: "scheduled",
      validationState: "valid",
      validationMessage: null,
      actions: [{ label: "View content", href: "/content/studio/preview-2" }],
    },
    {
      id: "pub-preview-2",
      title: "Customer proof: Acme Ltd case study",
      preview: null,
      channel: "Instagram",
      accountName: "Cresco AI",
      scheduledAt: null,
      campaign: null,
      status: "failed",
      validationState: "error",
      validationMessage: "Instagram carousel requires at least one image asset.",
      actions: [{ label: "Retry", href: "/operations/publishing?retry=pub-preview-2" }],
    },
  ],
  consistencyGaps: [
    { channel: "LinkedIn", message: "No LinkedIn content scheduled for the next 5 days." },
  ],
  bestTimeWindows: [
    {
      channel: "LinkedIn",
      dayOfWeek: "Tuesday",
      hourRange: "08:00–10:00",
      engagementLift: 3.2,
      confidence: "medium",
      sampleSize: 14,
      actionLabel: "Use this publishing window",
    },
  ],
  communityOpportunities: [],
  insights: [
    {
      id: "organic-opportunity-LINKEDIN",
      type: "organic",
      severity: "medium",
      title: "LinkedIn is outperforming organic baseline",
      explanation:
        "LinkedIn delivered a 4.70% engagement rate during last 30 days, above the organic average of 3.20%.",
      evidence: [
        { label: "Channel engagement rate", value: "4.70%" },
        { label: "Organic average", value: "3.20%" },
        { label: "Published posts", value: "12" },
      ],
      estimatedImpact: "Create more content in this high-performing format",
      action: { label: "Create Content", href: "/content/studio/new" },
      category: "organic",
      generatedAt: new Date().toISOString(),
      confidence: 0.78,
    },
  ],
  channelMetrics: [
    {
      provider: "LINKEDIN",
      label: "LinkedIn",
      reach: 98400,
      engagementRate: 4.7,
      followersGained: 820,
      clicks: 1240,
      connected: true,
    },
    {
      provider: "X",
      label: "X",
      reach: 41200,
      engagementRate: 2.1,
      followersGained: 120,
      clicks: 312,
      connected: true,
    },
    {
      provider: "INSTAGRAM",
      label: "Instagram",
      reach: null,
      engagementRate: null,
      followersGained: null,
      clicks: null,
      connected: false,
    },
  ],
  providers: ORGANIC_PROVIDER_REGISTRY.map((provider) => ({
    ...provider,
    availability:
      provider.provider === "LINKEDIN" || provider.provider === "X"
        ? "connected"
        : provider.availability,
    analytics:
      provider.provider === "LINKEDIN" || provider.provider === "X" ? true : provider.analytics,
    publish:
      provider.provider === "LINKEDIN" || provider.provider === "X" ? true : provider.publish,
  })),
};
