export const PROVIDER_OAUTH_STATE_TTL_MS = 10 * 60 * 1000;
export const PROVIDER_OAUTH_STATE_MAX_AGE_MS = PROVIDER_OAUTH_STATE_TTL_MS;

export const PROVIDER_REQUEST_TIMEOUT_MS = 30_000;
export const PROVIDER_MAX_RETRIES = 3;
export const PROVIDER_RETRY_BASE_DELAY_MS = 1_000;
export const PROVIDER_RETRY_MAX_DELAY_MS = 30_000;
export const PROVIDER_RETRY_JITTER_FACTOR = 0.2;

export const PROVIDER_WEBHOOK_TIMESTAMP_TOLERANCE_MS = 5 * 60 * 1000;
export const PROVIDER_WEBHOOK_MAX_RETRIES = 5;

export const PROVIDER_CIRCUIT_FAILURE_THRESHOLD = 5;
export const PROVIDER_CIRCUIT_RESET_MS = 60_000;

export const PROVIDER_ALLOWED_RETURN_URL_PREFIXES = ["/integrations", "/settings", "/connectors"] as const;

export const PROVIDER_CREDENTIAL_FINGERPRINT_LENGTH = 4;
