import type { ProviderDefinition } from "@/lib/providers/types";

function disabledProvider(
  partial: Omit<ProviderDefinition, "enabled" | "apiVersionStatus" | "requiresApproval"> &
    Partial<Pick<ProviderDefinition, "apiVersionStatus" | "requiresApproval" | "enabled">>,
): ProviderDefinition {
  return {
    enabled: false,
    apiVersionStatus: "CURRENT",
    requiresApproval: true,
    ...partial,
  };
}

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  // Social
  disabledProvider({
    key: "meta",
    displayName: "Meta",
    category: "SOCIAL",
    authType: "OAUTH2_PKCE",
    capabilities: ["PUBLISHING", "ANALYTICS_PULL", "OAUTH_CONNECT", "WEBHOOK_INGEST"],
    supportedEnvironments: ["SANDBOX", "PRODUCTION"],
    apiVersion: "v19.0",
    requiredConfigFields: [],
    optionalConfigFields: ["appId"],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: true,
    documentationUrl: "https://developers.facebook.com/docs/",
    oauthScopes: { default: ["pages_show_list", "pages_read_engagement"] },
  }),
  disabledProvider({
    key: "instagram",
    displayName: "Instagram",
    category: "SOCIAL",
    authType: "OAUTH2_PKCE",
    capabilities: ["PUBLISHING", "ANALYTICS_PULL", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v19.0",
    requiredConfigFields: [],
    optionalConfigFields: [],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: true,
    documentationUrl: "https://developers.facebook.com/docs/instagram-api/",
  }),
  disabledProvider({
    key: "facebook",
    displayName: "Facebook",
    category: "SOCIAL",
    authType: "OAUTH2_PKCE",
    capabilities: ["PUBLISHING", "ANALYTICS_PULL", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v19.0",
    requiredConfigFields: [],
    optionalConfigFields: [],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: true,
  }),
  disabledProvider({
    key: "linkedin",
    displayName: "LinkedIn",
    category: "SOCIAL",
    authType: "OAUTH2_AUTHORIZATION_CODE",
    capabilities: ["PUBLISHING", "ANALYTICS_PULL", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v2",
    requiredConfigFields: [],
    optionalConfigFields: [],
    webhookSupport: false,
    pushSupport: true,
    pullSupport: true,
    documentationUrl: "https://learn.microsoft.com/en-us/linkedin/",
  }),
  disabledProvider({
    key: "tiktok",
    displayName: "TikTok",
    category: "SOCIAL",
    authType: "OAUTH2_PKCE",
    capabilities: ["PUBLISHING", "OAUTH_CONNECT"],
    supportedEnvironments: ["SANDBOX", "PRODUCTION"],
    apiVersion: "v2",
    requiredConfigFields: [],
    optionalConfigFields: [],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: false,
  }),
  disabledProvider({
    key: "x",
    displayName: "X (Twitter)",
    category: "SOCIAL",
    authType: "OAUTH2_PKCE",
    capabilities: ["PUBLISHING", "ANALYTICS_PULL", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v2",
    requiredConfigFields: [],
    optionalConfigFields: [],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: true,
  }),
  disabledProvider({
    key: "youtube",
    displayName: "YouTube",
    category: "SOCIAL",
    authType: "OAUTH2_AUTHORIZATION_CODE",
    capabilities: ["PUBLISHING", "ANALYTICS_PULL", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v3",
    requiredConfigFields: [],
    optionalConfigFields: [],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: true,
  }),
  disabledProvider({
    key: "pinterest",
    displayName: "Pinterest",
    category: "SOCIAL",
    authType: "OAUTH2_AUTHORIZATION_CODE",
    capabilities: ["PUBLISHING", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v5",
    requiredConfigFields: [],
    optionalConfigFields: [],
    webhookSupport: false,
    pushSupport: true,
    pullSupport: false,
  }),

  // Analytics
  disabledProvider({
    key: "google-analytics",
    displayName: "Google Analytics 4",
    category: "ANALYTICS",
    authType: "OAUTH2_AUTHORIZATION_CODE",
    capabilities: ["ANALYTICS_PULL", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v1beta",
    requiredConfigFields: ["propertyId"],
    optionalConfigFields: [],
    webhookSupport: false,
    pushSupport: false,
    pullSupport: true,
    documentationUrl: "https://developers.google.com/analytics/devguides/reporting/data/v1",
  }),
  disabledProvider({
    key: "google-search-console",
    displayName: "Google Search Console",
    category: "SEO",
    authType: "OAUTH2_AUTHORIZATION_CODE",
    capabilities: ["ANALYTICS_PULL", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v1",
    requiredConfigFields: ["siteUrl"],
    optionalConfigFields: [],
    webhookSupport: false,
    pushSupport: false,
    pullSupport: true,
  }),
  disabledProvider({
    key: "google-ads",
    displayName: "Google Ads",
    category: "ADVERTISING",
    authType: "OAUTH2_AUTHORIZATION_CODE",
    capabilities: ["ADVERTISING_MANAGE", "ADVERTISING_REPORT", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v17",
    requiredConfigFields: ["customerId"],
    optionalConfigFields: ["developerToken"],
    webhookSupport: false,
    pushSupport: true,
    pullSupport: true,
  }),
  disabledProvider({
    key: "meta-ads",
    displayName: "Meta Ads",
    category: "ADVERTISING",
    authType: "OAUTH2_PKCE",
    capabilities: ["ADVERTISING_MANAGE", "ADVERTISING_REPORT", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v19.0",
    requiredConfigFields: ["adAccountId"],
    optionalConfigFields: [],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: true,
  }),
  disabledProvider({
    key: "linkedin-ads",
    displayName: "LinkedIn Ads",
    category: "ADVERTISING",
    authType: "OAUTH2_AUTHORIZATION_CODE",
    capabilities: ["ADVERTISING_MANAGE", "ADVERTISING_REPORT", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v2",
    requiredConfigFields: ["accountId"],
    optionalConfigFields: [],
    webhookSupport: false,
    pushSupport: true,
    pullSupport: true,
  }),
  disabledProvider({
    key: "tiktok-ads",
    displayName: "TikTok Ads",
    category: "ADVERTISING",
    authType: "OAUTH2_AUTHORIZATION_CODE",
    capabilities: ["ADVERTISING_MANAGE", "ADVERTISING_REPORT", "OAUTH_CONNECT"],
    supportedEnvironments: ["SANDBOX", "PRODUCTION"],
    apiVersion: "v1.3",
    requiredConfigFields: ["advertiserId"],
    optionalConfigFields: [],
    webhookSupport: false,
    pushSupport: true,
    pullSupport: true,
  }),
  disabledProvider({
    key: "microsoft-ads",
    displayName: "Microsoft Ads",
    category: "ADVERTISING",
    authType: "OAUTH2_AUTHORIZATION_CODE",
    capabilities: ["ADVERTISING_MANAGE", "ADVERTISING_REPORT", "OAUTH_CONNECT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v13",
    requiredConfigFields: ["accountId"],
    optionalConfigFields: [],
    webhookSupport: false,
    pushSupport: true,
    pullSupport: true,
  }),

  // Email
  disabledProvider({
    key: "resend",
    displayName: "Resend",
    category: "EMAIL",
    authType: "API_KEY",
    capabilities: ["EMAIL_SEND", "EMAIL_WEBHOOK"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v1",
    requiredConfigFields: ["apiKey"],
    optionalConfigFields: ["fromDomain"],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: false,
  }),
  disabledProvider({
    key: "sendgrid",
    displayName: "SendGrid",
    category: "EMAIL",
    authType: "API_KEY",
    capabilities: ["EMAIL_SEND", "EMAIL_WEBHOOK"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v3",
    requiredConfigFields: ["apiKey"],
    optionalConfigFields: [],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: false,
  }),
  disabledProvider({
    key: "postmark",
    displayName: "Postmark",
    category: "EMAIL",
    authType: "API_KEY",
    capabilities: ["EMAIL_SEND", "EMAIL_WEBHOOK"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v1",
    requiredConfigFields: ["serverToken"],
    optionalConfigFields: [],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: false,
  }),
  disabledProvider({
    key: "amazon-ses",
    displayName: "Amazon SES",
    category: "EMAIL",
    authType: "AWS_SIGNATURE",
    capabilities: ["EMAIL_SEND", "EMAIL_WEBHOOK"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "v2",
    requiredConfigFields: ["region", "accessKeyId", "secretAccessKey"],
    optionalConfigFields: [],
    webhookSupport: true,
    pushSupport: true,
    pullSupport: false,
  }),
  disabledProvider({
    key: "smtp",
    displayName: "SMTP",
    category: "EMAIL",
    authType: "SMTP_CREDENTIALS",
    capabilities: ["EMAIL_SEND"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "1.0",
    requiredConfigFields: ["host", "port", "username", "password"],
    optionalConfigFields: ["fromAddress"],
    webhookSupport: false,
    pushSupport: true,
    pullSupport: false,
    requiresApproval: true,
  }),

  // Payments
  disabledProvider({
    key: "stripe",
    displayName: "Stripe",
    category: "PAYMENTS",
    authType: "API_KEY",
    capabilities: ["PAYMENT_SYNC", "WEBHOOK_INGEST"],
    supportedEnvironments: ["SANDBOX", "PRODUCTION"],
    apiVersion: "2024-06-20",
    requiredConfigFields: ["secretKey"],
    optionalConfigFields: ["webhookSecret"],
    webhookSupport: true,
    pushSupport: false,
    pullSupport: true,
    documentationUrl: "https://stripe.com/docs/api",
  }),

  // SEO and data
  disabledProvider({
    key: "licensed-rank-provider",
    displayName: "Licensed Rank Provider",
    category: "SEO",
    authType: "API_KEY",
    capabilities: ["SEARCH_RANK"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "1.0",
    requiredConfigFields: ["apiKey"],
    optionalConfigFields: [],
    webhookSupport: false,
    pushSupport: false,
    pullSupport: true,
  }),
  disabledProvider({
    key: "csv-import",
    displayName: "CSV Import",
    category: "DATA",
    authType: "NONE",
    capabilities: ["DATA_IMPORT"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "1.0",
    requiredConfigFields: [],
    optionalConfigFields: [],
    webhookSupport: false,
    pushSupport: false,
    pullSupport: true,
    enabled: true,
    requiresApproval: false,
  }),
  disabledProvider({
    key: "first-party-crawler",
    displayName: "First-Party Crawler",
    category: "SEO",
    authType: "INTERNAL",
    capabilities: ["CRAWL"],
    supportedEnvironments: ["PRODUCTION"],
    apiVersion: "1.0",
    requiredConfigFields: [],
    optionalConfigFields: ["maxPages"],
    webhookSupport: false,
    pushSupport: false,
    pullSupport: true,
    enabled: true,
    requiresApproval: false,
  }),
];
